/*
 * Created on 13 lug 2017 ( Time 12:07:28 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.whitepaper.business.service.custom;

import java.util.Date;

public interface UtenteActionCustomService { 
	
	
	public boolean checkNumStrappaGreaterMax(int idUte, Date dataIn);
		
	public boolean saveNumActionPerIdUteAndData(int idUte, String codAction, Date dataIn);
	
}
