/*
 * Created on 2022-11-03 ( Time 15:20:01 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
package org.whitepaper.business.service;

import java.util.List;

import org.whitepaper.bean.MessaggioTags;

/**
 * Business Service Interface for entity MessaggioTags.
 */
public interface MessaggioTagsService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param idTag
	 * @return entity
	 */
	MessaggioTags findById( Integer idTag  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<MessaggioTags> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	MessaggioTags save(MessaggioTags entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	MessaggioTags update(MessaggioTags entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	MessaggioTags create(MessaggioTags entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param idTag
	 */
	void delete( Integer idTag );


}
