/*
 * Created on 31 gen 2023 ( Time 08:05:09 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.whitepaper.bean;

import java.io.Serializable;

import javax.validation.constraints.*;

import java.util.Date;

public class Faq implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Integer idFaq;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @NotNull
    @Size( min = 1, max = 100 )
    private String domFaq;

    @Size( max = 5000 )
    private String risFaq;


    private Date datFaq;

    @Size( max = 4 )
    private String codStaFaq;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setIdFaq( Integer idFaq ) {
        this.idFaq = idFaq ;
    }

    public Integer getIdFaq() {
        return this.idFaq;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setDomFaq( String domFaq ) {
        this.domFaq = domFaq;
    }
    public String getDomFaq() {
        return this.domFaq;
    }

    public void setRisFaq( String risFaq ) {
        this.risFaq = risFaq;
    }
    public String getRisFaq() {
        return this.risFaq;
    }

    public void setDatFaq( Date datFaq ) {
        this.datFaq = datFaq;
    }
    public Date getDatFaq() {
        return this.datFaq;
    }

    public void setCodStaFaq( String codStaFaq ) {
        this.codStaFaq = codStaFaq;
    }
    public String getCodStaFaq() {
        return this.codStaFaq;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idFaq);
        sb.append("|");
        sb.append(domFaq);
        sb.append("|");
        sb.append(risFaq);
        sb.append("|");
        sb.append(datFaq);
        sb.append("|");
        sb.append(codStaFaq);
        return sb.toString(); 
    } 


}
