/*
 * Created on 2022-11-08 ( Time 12:43:44 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
// This Bean has a basic Primary Key (not composite) 

package org.whitepaper.bean;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;



public class UtenteAction implements Serializable {

    private static final long serialVersionUID = 1L;

    private int idUteAct;
    private int idUte;
    private String codAction;
    private Date datAction;
    private int numAction;
    private Date datUltMov;

    
	public int getIdUteAct() {
		return idUteAct;
	}

	public void setIdUteAct(int idUteAct) {
		this.idUteAct = idUteAct;
	}

	public int getIdUte() {
		return idUte;
	}

	public void setIdUte(int idUte) {
		this.idUte = idUte;
	}

	public String getCodAction() {
		return codAction;
	}

	public void setCodAction(String codAction) {
		this.codAction = codAction;
	}

	public Date getDatAction() {
		return datAction;
	}

	public void setDatAction(Date datAction) {
		this.datAction = datAction;
	}

	public Date getDatUltMov() {
		return datUltMov;
	}

	public void setDatUltMov(Date datUltMov) {
		this.datUltMov = datUltMov;
	}

	public int getNumAction() {
		return numAction;
	}

	public void setNumAction(int numAction) {
		this.numAction = numAction;
	}
	    
    

   
}
