/*
 * Created on 13 lug 2017 ( Time 12:06:10 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.whitepaper.web.controller.custom;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
//--- Common classes
import org.whitepaper.web.common.AbstractController;

/**
 * Spring MVC controller for 'AnaUtente' management.
 */
@Controller
@RequestMapping("/profilo")
public class ProfiloController extends AbstractController {

	//--- Variables names ( to be used in JSP with Expression Language )
	private static final String MAIN_ENTITY_NAME = "anaUtente";
	

	//--- JSP pages names ( View name in the MVC model )
	private static final String JSP_FORM   = "profiloute/form";
	

	//--- SAVE ACTION ( in the HTML form )
	
	private static final String SAVE_ACTION_UPDATE   = "/profilo/update";

	//--- Main entity service

	//--------------------------------------------------------------------------------------
	/**
	 * Default constructor
	 */
	public ProfiloController() {
		super(ProfiloController.class, MAIN_ENTITY_NAME );
		log("ProfiloController created.");
	}

	//--------------------------------------------------------------------------------------
	// Spring MVC model management
	//--------------------------------------------------------------------------------------
	/**
	 * Populates the combo-box "items" for the referenced entity "AnaSquadra"
	 * @param model
	 */


	

}
