/*
 * Created on 2022-11-03 ( Time 15:19:50 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
package org.whitepaper.web.listitem;

import org.whitepaper.bean.AnaUtente;
import org.whitepaper.web.common.ListItem;

public class AnaUtenteListItem implements ListItem {

	private final String value ;
	private final String label ;
	
	public AnaUtenteListItem(AnaUtente anaUtente) {
		super();

		this.value = ""
			 + anaUtente.getIdUte()
		;

		//TODO : Define here the attributes to be displayed as the label
		this.label = anaUtente.toString();
	}

	@Override
	public String getValue() {
		return value;
	}

	@Override
	public String getLabel() {
		return label;
	}

}
