/*
 * Created on 9 gen 2023 ( Time 14:26:24 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.whitepaper.business.service;

import java.util.List;

import org.whitepaper.bean.MessaggioAdmin;

/**
 * Business Service Interface for entity MessaggioAdmin.
 */
public interface MessaggioAdminService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param idMsg
	 * @return entity
	 */
	MessaggioAdmin findById( Integer idMsg  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<MessaggioAdmin> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	MessaggioAdmin save(MessaggioAdmin entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	MessaggioAdmin update(MessaggioAdmin entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	MessaggioAdmin create(MessaggioAdmin entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param idMsg
	 */
	void delete( Integer idMsg );


}
