/*
 * Created on 2023-12-11 ( Time 14:18:11 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
package org.whitepaper.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import org.whitepaper.bean.TipInfo;
import org.whitepaper.bean.jpa.TipInfoEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class TipInfoServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public TipInfoServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'TipInfoEntity' to 'TipInfo'
	 * @param tipInfoEntity
	 */
	public TipInfo mapTipInfoEntityToTipInfo(TipInfoEntity tipInfoEntity) {
		if(tipInfoEntity == null) {
			return null;
		}

		//--- Generic mapping 
		TipInfo tipInfo = map(tipInfoEntity, TipInfo.class);

		return tipInfo;
	}
	
	/**
	 * Mapping from 'TipInfo' to 'TipInfoEntity'
	 * @param tipInfo
	 * @param tipInfoEntity
	 */
	public void mapTipInfoToTipInfoEntity(TipInfo tipInfo, TipInfoEntity tipInfoEntity) {
		if(tipInfo == null) {
			return;
		}

		//--- Generic mapping 
		map(tipInfo, tipInfoEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}