/*
 * Created on 2022-11-03 ( Time 15:19:50 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
package org.whitepaper.web.controller;

import java.util.LinkedList;
import java.util.List;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;
//--- Entities
import org.whitepaper.bean.AnaUtente;
import org.whitepaper.bean.TipProfilo;
//--- Services 
import org.whitepaper.business.service.AnaUtenteService;
import org.whitepaper.business.service.TipProfiloService;
import org.whitepaper.utility.EncoderGenerator;
//--- Common classes
import org.whitepaper.web.common.AbstractController;
import org.whitepaper.web.common.FormMode;
import org.whitepaper.web.common.Message;
import org.whitepaper.web.common.MessageType;
//--- List Items 
import org.whitepaper.web.listitem.TipProfiloListItem;

/**
 * Spring MVC controller for 'AnaUtente' management.
 */
@Controller
@RequestMapping("/anaUtente")
public class AnaUtenteController extends AbstractController {

	//--- Variables names ( to be used in JSP with Expression Language )
	private static final String MAIN_ENTITY_NAME = "anaUtente";
	private static final String MAIN_LIST_NAME   = "list";

	//--- JSP pages names ( View name in the MVC model )
	private static final String JSP_FORM   = "anaUtente/form";
	private static final String JSP_LIST   = "anaUtente/list";

	//--- SAVE ACTION ( in the HTML form )
	private static final String SAVE_ACTION_CREATE   = "/anaUtente/create";
	private static final String SAVE_ACTION_UPDATE   = "/anaUtente/update";

	//--- Main entity service
	@Resource
    private AnaUtenteService anaUtenteService; // Injected by Spring
	//--- Other service(s)
	@Resource
    private TipProfiloService tipProfiloService; // Injected by Spring

	//--------------------------------------------------------------------------------------
	/**
	 * Default constructor
	 */
	public AnaUtenteController() {
		super(AnaUtenteController.class, MAIN_ENTITY_NAME );
		log("AnaUtenteController created.");
	}

	//--------------------------------------------------------------------------------------
	// Spring MVC model management
	//--------------------------------------------------------------------------------------
	/**
	 * Populates the combo-box "items" for the referenced entity "TipProfilo"
	 * @param model
	 */
	private void populateListOfTipProfiloItems(Model model) {
		List<TipProfilo> list = tipProfiloService.findAll();
		List<TipProfiloListItem> items = new LinkedList<TipProfiloListItem>();
		for ( TipProfilo tipProfilo : list ) {
			items.add(new TipProfiloListItem( tipProfilo ) );
		}
		model.addAttribute("listOfTipProfiloItems", items ) ;
	}


	/**
	 * Populates the Spring MVC model with the given entity and eventually other useful data
	 * @param model
	 * @param anaUtente
	 */
	private void populateModel(Model model, AnaUtente anaUtente, FormMode formMode) {
		//--- Main entity
		model.addAttribute(MAIN_ENTITY_NAME, anaUtente);
		if ( formMode == FormMode.CREATE ) {
			model.addAttribute(MODE, MODE_CREATE); // The form is in "create" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_CREATE); 			
			//--- Other data useful in this screen in "create" mode (all fields)
			populateListOfTipProfiloItems(model);
		}
		else if ( formMode == FormMode.UPDATE ) {
			model.addAttribute(MODE, MODE_UPDATE); // The form is in "update" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_UPDATE); 			
			//--- Other data useful in this screen in "update" mode (only non-pk fields)
			populateListOfTipProfiloItems(model);
		}
	}

	//--------------------------------------------------------------------------------------
	// Request mapping
	//--------------------------------------------------------------------------------------
	/**
	 * Shows a list with all the occurrences of AnaUtente found in the database
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping()
	public String list(Model model) {
		log("Action 'list'");
		List<AnaUtente> list = anaUtenteService.findAll();
		model.addAttribute(MAIN_LIST_NAME, list);		
		return JSP_LIST;
	}

	/**
	 * Shows a form page in order to create a new AnaUtente
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping("/form")
	public String formForCreate(Model model) {
		log("Action 'formForCreate'");
		//--- Populates the model with a new instance
		AnaUtente anaUtente = new AnaUtente();	
		populateModel( model, anaUtente, FormMode.CREATE);
		return JSP_FORM;
	}

	/**
	 * Shows a form page in order to update an existing AnaUtente
	 * @param model Spring MVC model
	 * @param idUte  primary key element
	 * @return
	 */
	@RequestMapping(value = "/form/{idUte}")
	public String formForUpdate(Model model, @PathVariable("idUte") Integer idUte ) {
		log("Action 'formForUpdate'");
		//--- Search the entity by its primary key and stores it in the model 
		AnaUtente anaUtente = anaUtenteService.findById(idUte);
		populateModel( model, anaUtente, FormMode.UPDATE);		
		return JSP_FORM;
	}

	/**
	 * 'CREATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param anaUtente  entity to be created
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/create" ) // GET or POST
	public String create(AnaUtente anaUtente, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'create'");
		try {
			if (!bindingResult.hasErrors()) {
				AnaUtente anaUtenteCreated = anaUtenteService.create(anaUtente); 
				model.addAttribute(MAIN_ENTITY_NAME, anaUtenteCreated);

				//---
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				return redirectToForm(httpServletRequest, anaUtenteCreated.getIdUte() );
			} else {
				populateModel( model, anaUtente, FormMode.CREATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			log("Action 'create' : Exception - " + e.getMessage() );
			messageHelper.addException(model, "anaUtente.error.create", e);
			populateModel( model, anaUtente, FormMode.CREATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'UPDATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param anaUtente  entity to be updated
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/update" ) // GET or POST
	public String update(AnaUtente anaUtente, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'update'");
		try {
			if (!bindingResult.hasErrors()) {
				//--- Perform database operations
				anaUtente.setPwd(EncoderGenerator.encode(anaUtente.getPwd()));
				AnaUtente anaUtenteSaved = anaUtenteService.update(anaUtente);
				model.addAttribute(MAIN_ENTITY_NAME, anaUtenteSaved);
				//--- Set the result message
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				log("Action 'update' : update done - redirect");
				return redirectToForm(httpServletRequest, anaUtenteSaved.getIdUte());
			} else {
				log("Action 'update' : binding errors");
				populateModel( model, anaUtente, FormMode.UPDATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			messageHelper.addException(model, "anaUtente.error.update", e);
			log("Action 'update' : Exception - " + e.getMessage() );
			populateModel( model, anaUtente, FormMode.UPDATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'DELETE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param redirectAttributes
	 * @param idUte  primary key element
	 * @return
	 */
	@RequestMapping(value = "/delete/{idUte}") // GET or POST
	public String delete(RedirectAttributes redirectAttributes, @PathVariable("idUte") Integer idUte) {
		log("Action 'delete'" );
		try {
			anaUtenteService.delete( idUte );
			//--- Set the result message
			messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"delete.ok"));	
		} catch(Exception e) {
			messageHelper.addException(redirectAttributes, "anaUtente.error.delete", e);
		}
		return redirectToList();
	}

}
