/*
 * Created on 13 lug 2017 ( Time 12:06:09 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.whitepaper.web.controller;

import org.springframework.stereotype.Controller;
import org.whitepaper.web.common.AbstractController;


@Controller
public class BaseController extends AbstractController  {

		

	
	private static final String MAIN_ENTITY_NAME = "assUteLega";
	
	public BaseController() {
		super(BaseController.class, MAIN_ENTITY_NAME );
		log("ClassificaBaseController created.");
	}
	

}
