/*
 * Created on 13 lug 2017 ( Time 12:06:09 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.whitepaper.web.controller;

import java.util.List;

import javax.annotation.Resource;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;
import org.whitepaper.bean.AnaFaq;
import org.whitepaper.business.service.AnaFaqService;
import org.whitepaper.utility.ConstantsDefinition;
import org.whitepaper.web.common.AbstractController;


@Controller
@RequestMapping("/info")
public class InfoController extends AbstractController {
	
	public InfoController() {
		super(AbstractController.class, MAIN_ENTITY_NAME );
		log("InfoController created.");
	}
	
	private static final String JSP_WHO = "info/who";
	private static final String JSP_FAQS = "info/faqs";	
	private static final String JSP_CONTATTI = "info/contatti";
	private static final String MAIN_ENTITY_NAME = "faq";
	

	@Resource
	private AnaFaqService anafaqService; // Injected by Spring

	
	@RequestMapping(value = "/faqs") 
	public String listFaqs(Model model) {
		
		log("Action 'listFaqs'");				
		
		//lettura delle faq pubblicate
		List<AnaFaq> theListFaq = anafaqService.loadFaqsPerStato(ConstantsDefinition.COD_FAQ_PUBBLICATA);		
		model.addAttribute("theListFaq", theListFaq);
		
		return JSP_FAQS;
	}
	
	@RequestMapping(value = "/faqs_mobile", method = RequestMethod.GET)
	@ResponseBody // Indica che la risposta deve essere serializzata come JSON
	public List<AnaFaq> listFaqsMobile() {
	    
	    log("Action 'listFaqs'");                
	    
	    // Lettura delle faq pubblicate
	    List<AnaFaq> theListFaq = anafaqService.loadFaqsPerStato(ConstantsDefinition.COD_FAQ_PUBBLICATA);        
	    
	    return theListFaq; // Restituisce direttamente la lista come risposta JSON
	}
	
	
	@RequestMapping(value = "/who") 
	public String whoPage(Model model) {
		
		log("Action 'whoPage'");				
		
		return JSP_WHO;
	}
	
	@RequestMapping(value = "/contatti") 
	public String contattiPage(Model model) {
		
		log("Action 'contattiPage'");				
		
		return JSP_CONTATTI;
	}
	
}
