/*
 * Created on 9 gen 2023 ( Time 14:25:41 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.whitepaper.web.controller;

import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;
import org.whitepaper.bean.CatMessaggio;
import org.whitepaper.bean.MessaggioAdmin;
import org.whitepaper.bean.TipMessaggio;
import org.whitepaper.business.service.CatMessaggioService;
import org.whitepaper.business.service.MessaggioAdminService;
import org.whitepaper.business.service.TipMessaggioService;
import org.whitepaper.utility.ConstantsDefinition;
import org.whitepaper.web.common.AbstractController;
import org.whitepaper.web.common.FormMode;
import org.whitepaper.web.common.Message;
import org.whitepaper.web.common.MessageType;
import org.whitepaper.web.listitem.CatMessaggioListItem;
import org.whitepaper.web.listitem.TipMessaggioListItem;

/**
 * Spring MVC controller for 'MessaggioAdmin' management.
 */
@Controller
@RequestMapping("/messaggioAdmin")
public class MessaggioAdminController extends AbstractController {

	//--- Variables names ( to be used in JSP with Expression Language )
	private static final String MAIN_ENTITY_NAME = "messaggioAdmin";
	private static final String MAIN_LIST_NAME   = "list";

	//--- JSP pages names ( View name in the MVC model )
	private static final String JSP_FORM   = "messaggioAdmin/form";
	private static final String JSP_LIST   = "messaggioAdmin/list";

	//--- SAVE ACTION ( in the HTML form )
	private static final String SAVE_ACTION_CREATE   = "/messaggioAdmin/create";
	private static final String SAVE_ACTION_UPDATE   = "/messaggioAdmin/update";

	//--- Main entity service
	@Resource
    private MessaggioAdminService messaggioAdminService; // Injected by Spring
	//--- Other service(s)
	@Resource
    private TipMessaggioService tipMessaggioService; // Injected by Spring
	@Resource
    private CatMessaggioService catMessaggioService; // Injected by Spring

	//--------------------------------------------------------------------------------------
	/**
	 * Default constructor
	 */
	public MessaggioAdminController() {
		super(MessaggioAdminController.class, MAIN_ENTITY_NAME );
		log("MessaggioAdminController created.");
	}

	//--------------------------------------------------------------------------------------
	// Spring MVC model management
	//--------------------------------------------------------------------------------------
	/**
	 * Populates the combo-box "items" for the referenced entity "TipMessaggio"
	 * @param model
	 */
	private void populateListOfTipMessaggioItems(Model model) {
		//List<TipMessaggio> list = tipMessaggioService.findAll();
		
		//List<TipMessaggio> list = tipMessaggioService.findAll();
		List<TipMessaggio> list = new ArrayList<TipMessaggio>();
		TipMessaggio tipMsg = new TipMessaggio(ConstantsDefinition.COD_TIP_MSG_BOZ, ConstantsDefinition.DES_TIP_MSG_BOZ);
		list.add(tipMsg);
		tipMsg = new TipMessaggio(ConstantsDefinition.COD_TIP_MSG_INV, ConstantsDefinition.DES_TIP_MSG_INV);
		list.add(tipMsg);
		
		List<TipMessaggioListItem> items = new LinkedList<TipMessaggioListItem>();
		for ( TipMessaggio tipMessaggio : list ) {
			items.add(new TipMessaggioListItem( tipMessaggio ) );
		}
		model.addAttribute("listOfTipMessaggioItems", items ) ;
	}

	/**
	 * Populates the combo-box "items" for the referenced entity "CatMessaggio"
	 * @param model
	 */
	private void populateListOfCatMessaggioItems(Model model) {
		List<CatMessaggio> list = catMessaggioService.findAll();
		List<CatMessaggioListItem> items = new LinkedList<CatMessaggioListItem>();
		for ( CatMessaggio catMessaggio : list ) {
			items.add(new CatMessaggioListItem( catMessaggio ) );
		}
		model.addAttribute("listOfCatMessaggioItems", items ) ;
	}


	/**
	 * Populates the Spring MVC model with the given entity and eventually other useful data
	 * @param model
	 * @param messaggioAdmin
	 */
	private void populateModel(Model model, MessaggioAdmin messaggioAdmin, FormMode formMode) {
		//--- Main entity
		model.addAttribute(MAIN_ENTITY_NAME, messaggioAdmin);
		if ( formMode == FormMode.CREATE ) {
			model.addAttribute(MODE, MODE_CREATE); // The form is in "create" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_CREATE); 			
			//--- Other data useful in this screen in "create" mode (all fields)
			populateListOfTipMessaggioItems(model);
			populateListOfCatMessaggioItems(model);
		}
		else if ( formMode == FormMode.UPDATE ) {
			model.addAttribute(MODE, MODE_UPDATE); // The form is in "update" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_UPDATE); 			
			//--- Other data useful in this screen in "update" mode (only non-pk fields)
			populateListOfTipMessaggioItems(model);
			populateListOfCatMessaggioItems(model);
		}
	}

	//--------------------------------------------------------------------------------------
	// Request mapping
	//--------------------------------------------------------------------------------------
	/**
	 * Shows a list with all the occurrences of MessaggioAdmin found in the database
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping()
	public String list(Model model) {
		log("Action 'list'");
		List<MessaggioAdmin> list = messaggioAdminService.findAll();
		model.addAttribute(MAIN_LIST_NAME, list);		
		return JSP_LIST;
	}

	/**
	 * Shows a form page in order to create a new MessaggioAdmin
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping("/form")
	public String formForCreate(Model model) {
		log("Action 'formForCreate'");
		//--- Populates the model with a new instance
		MessaggioAdmin messaggioAdmin = new MessaggioAdmin();	
		populateModel( model, messaggioAdmin, FormMode.CREATE);
		return JSP_FORM;
	}

	/**
	 * Shows a form page in order to update an existing MessaggioAdmin
	 * @param model Spring MVC model
	 * @param idMsg  primary key element
	 * @return
	 */
	@RequestMapping(value = "/form/{idMsg}")
	public String formForUpdate(Model model, @PathVariable("idMsg") Integer idMsg ) {
		log("Action 'formForUpdate'");
		//--- Search the entity by its primary key and stores it in the model 
		MessaggioAdmin messaggioAdmin = messaggioAdminService.findById(idMsg);
		populateModel( model, messaggioAdmin, FormMode.UPDATE);		
		return JSP_FORM;
	}

	/**
	 * 'CREATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param messaggioAdmin  entity to be created
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/create" ) // GET or POST
	public String create(MessaggioAdmin messaggioAdmin, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'create'");
		try {
			if (!bindingResult.hasErrors()) {
				MessaggioAdmin messaggioAdminCreated = messaggioAdminService.create(messaggioAdmin); 
				model.addAttribute(MAIN_ENTITY_NAME, messaggioAdminCreated);

				//---
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				return redirectToForm(httpServletRequest, messaggioAdminCreated.getIdMsg() );
			} else {
				populateModel( model, messaggioAdmin, FormMode.CREATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			log("Action 'create' : Exception - " + e.getMessage() );
			messageHelper.addException(model, "messaggioAdmin.error.create", e);
			populateModel( model, messaggioAdmin, FormMode.CREATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'UPDATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param messaggioAdmin  entity to be updated
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/update" ) // GET or POST
	public String update(MessaggioAdmin messaggioAdmin, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'update'");
		try {
			if (!bindingResult.hasErrors()) {
				//--- Perform database operations
				MessaggioAdmin messaggioAdminSaved = messaggioAdminService.update(messaggioAdmin);
				model.addAttribute(MAIN_ENTITY_NAME, messaggioAdminSaved);
				//--- Set the result message
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				log("Action 'update' : update done - redirect");
				return redirectToForm(httpServletRequest, messaggioAdmin.getIdMsg());
			} else {
				log("Action 'update' : binding errors");
				populateModel( model, messaggioAdmin, FormMode.UPDATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			messageHelper.addException(model, "messaggioAdmin.error.update", e);
			log("Action 'update' : Exception - " + e.getMessage() );
			populateModel( model, messaggioAdmin, FormMode.UPDATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'DELETE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param redirectAttributes
	 * @param idMsg  primary key element
	 * @return
	 */
	@RequestMapping(value = "/delete/{idMsg}") // GET or POST
	public String delete(RedirectAttributes redirectAttributes, @PathVariable("idMsg") Integer idMsg) {
		log("Action 'delete'" );
		try {
			messaggioAdminService.delete( idMsg );
			//--- Set the result message
			messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"delete.ok"));	
		} catch(Exception e) {
			messageHelper.addException(redirectAttributes, "messaggioAdmin.error.delete", e);
		}
		return redirectToList();
	}

}
