/*
 * Created on 2022-11-03 ( Time 15:20:01 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
package org.whitepaper.web.controller;

import java.util.List;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

//--- Common classes
import org.whitepaper.web.common.AbstractController;
import org.whitepaper.web.common.FormMode;
import org.whitepaper.web.common.Message;
import org.whitepaper.web.common.MessageType;

//--- Entities
import org.whitepaper.bean.TipMessaggio;

//--- Services 
import org.whitepaper.business.service.TipMessaggioService;


/**
 * Spring MVC controller for 'TipMessaggio' management.
 */
@Controller
@RequestMapping("/tipMessaggio")
public class TipMessaggioController extends AbstractController {

	//--- Variables names ( to be used in JSP with Expression Language )
	private static final String MAIN_ENTITY_NAME = "tipMessaggio";
	private static final String MAIN_LIST_NAME   = "list";

	//--- JSP pages names ( View name in the MVC model )
	private static final String JSP_FORM   = "tipMessaggio/form";
	private static final String JSP_LIST   = "tipMessaggio/list";

	//--- SAVE ACTION ( in the HTML form )
	private static final String SAVE_ACTION_CREATE   = "/tipMessaggio/create";
	private static final String SAVE_ACTION_UPDATE   = "/tipMessaggio/update";

	//--- Main entity service
	@Resource
    private TipMessaggioService tipMessaggioService; // Injected by Spring
	//--- Other service(s)

	//--------------------------------------------------------------------------------------
	/**
	 * Default constructor
	 */
	public TipMessaggioController() {
		super(TipMessaggioController.class, MAIN_ENTITY_NAME );
		log("TipMessaggioController created.");
	}

	//--------------------------------------------------------------------------------------
	// Spring MVC model management
	//--------------------------------------------------------------------------------------

	/**
	 * Populates the Spring MVC model with the given entity and eventually other useful data
	 * @param model
	 * @param tipMessaggio
	 */
	private void populateModel(Model model, TipMessaggio tipMessaggio, FormMode formMode) {
		//--- Main entity
		model.addAttribute(MAIN_ENTITY_NAME, tipMessaggio);
		if ( formMode == FormMode.CREATE ) {
			model.addAttribute(MODE, MODE_CREATE); // The form is in "create" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_CREATE); 			
			//--- Other data useful in this screen in "create" mode (all fields)
		}
		else if ( formMode == FormMode.UPDATE ) {
			model.addAttribute(MODE, MODE_UPDATE); // The form is in "update" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_UPDATE); 			
			//--- Other data useful in this screen in "update" mode (only non-pk fields)
		}
	}

	//--------------------------------------------------------------------------------------
	// Request mapping
	//--------------------------------------------------------------------------------------
	/**
	 * Shows a list with all the occurrences of TipMessaggio found in the database
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping()
	public String list(Model model) {
		log("Action 'list'");
		List<TipMessaggio> list = tipMessaggioService.findAll();
		model.addAttribute(MAIN_LIST_NAME, list);		
		return JSP_LIST;
	}

	/**
	 * Shows a form page in order to create a new TipMessaggio
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping("/form")
	public String formForCreate(Model model) {
		log("Action 'formForCreate'");
		//--- Populates the model with a new instance
		TipMessaggio tipMessaggio = new TipMessaggio();	
		populateModel( model, tipMessaggio, FormMode.CREATE);
		return JSP_FORM;
	}

	/**
	 * Shows a form page in order to update an existing TipMessaggio
	 * @param model Spring MVC model
	 * @param codTipMsg  primary key element
	 * @return
	 */
	@RequestMapping(value = "/form/{codTipMsg}")
	public String formForUpdate(Model model, @PathVariable("codTipMsg") String codTipMsg ) {
		log("Action 'formForUpdate'");
		//--- Search the entity by its primary key and stores it in the model 
		TipMessaggio tipMessaggio = tipMessaggioService.findById(codTipMsg);
		populateModel( model, tipMessaggio, FormMode.UPDATE);		
		return JSP_FORM;
	}

	/**
	 * 'CREATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param tipMessaggio  entity to be created
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/create" ) // GET or POST
	public String create(@Valid TipMessaggio tipMessaggio, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'create'");
		try {
			if (!bindingResult.hasErrors()) {
				TipMessaggio tipMessaggioCreated = tipMessaggioService.create(tipMessaggio); 
				model.addAttribute(MAIN_ENTITY_NAME, tipMessaggioCreated);

				//---
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				return redirectToForm(httpServletRequest, tipMessaggio.getCodTipMsg() );
			} else {
				populateModel( model, tipMessaggio, FormMode.CREATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			log("Action 'create' : Exception - " + e.getMessage() );
			messageHelper.addException(model, "tipMessaggio.error.create", e);
			populateModel( model, tipMessaggio, FormMode.CREATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'UPDATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param tipMessaggio  entity to be updated
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/update" ) // GET or POST
	public String update(@Valid TipMessaggio tipMessaggio, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'update'");
		try {
			if (!bindingResult.hasErrors()) {
				//--- Perform database operations
				TipMessaggio tipMessaggioSaved = tipMessaggioService.update(tipMessaggio);
				model.addAttribute(MAIN_ENTITY_NAME, tipMessaggioSaved);
				//--- Set the result message
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				log("Action 'update' : update done - redirect");
				return redirectToForm(httpServletRequest, tipMessaggio.getCodTipMsg());
			} else {
				log("Action 'update' : binding errors");
				populateModel( model, tipMessaggio, FormMode.UPDATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			messageHelper.addException(model, "tipMessaggio.error.update", e);
			log("Action 'update' : Exception - " + e.getMessage() );
			populateModel( model, tipMessaggio, FormMode.UPDATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'DELETE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param redirectAttributes
	 * @param codTipMsg  primary key element
	 * @return
	 */
	@RequestMapping(value = "/delete/{codTipMsg}") // GET or POST
	public String delete(RedirectAttributes redirectAttributes, @PathVariable("codTipMsg") String codTipMsg) {
		log("Action 'delete'" );
		try {
			tipMessaggioService.delete( codTipMsg );
			//--- Set the result message
			messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"delete.ok"));	
		} catch(Exception e) {
			messageHelper.addException(redirectAttributes, "tipMessaggio.error.delete", e);
		}
		return redirectToList();
	}

}
