/*
 * Created on 2023-12-11 ( Time 14:17:55 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
// This Bean has a basic Primary Key (not composite) 

package org.whitepaper.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;


import javax.persistence.*;

/**
 * Persistent class for entity stored in table "tip_info"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="tip_info", catalog="fogliobianco" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="TipInfoEntity.countAll", query="SELECT COUNT(x) FROM TipInfoEntity x" )
} )
public class TipInfoEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="cod_info", nullable=false, length=10)
    private String     codInfo      ;

    @Column(name="des_info", length=500)
    private String     desInfo      ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public TipInfoEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : cod_info ( VARCHAR ) 
    public void setCodInfo( String codInfo ) {
        this.codInfo = codInfo;
    }
    public String getCodInfo() {
        return this.codInfo;
    }

    //--- DATABASE MAPPING : des_info ( VARCHAR ) 
    public void setDesInfo( String desInfo ) {
        this.desInfo = desInfo;
    }
    public String getDesInfo() {
        return this.desInfo;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(codInfo);
        sb.append("|");
        sb.append(desInfo);
        return sb.toString(); 
    } 

}
