/*
 * Created on 17 mag 2018 ( Time 10:03:01 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.whitepaper.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import org.whitepaper.bean.AnaFaq;
import org.whitepaper.bean.jpa.AnaFaqEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class AnaFaqServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public AnaFaqServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'AnaFaqEntity' to 'AnaFaq'
	 * @param anaFaqEntity
	 */
	public AnaFaq mapAnaFaqEntityToAnaFaq(AnaFaqEntity anaFaqEntity) {
		if(anaFaqEntity == null) {
			return null;
		}

		//--- Generic mapping 
		AnaFaq anaFaq = map(anaFaqEntity, AnaFaq.class);
		return anaFaq;
	}
	
	/**
	 * Mapping from 'AnaFaq' to 'AnaFaqEntity'
	 * @param anaFaq
	 * @param anaFaqEntity
	 */
	public void mapAnaFaqToAnaFaqEntity(AnaFaq anaFaq, AnaFaqEntity anaFaqEntity) {
		if(anaFaq == null) {
			return;
		}

		//--- Generic mapping 
		map(anaFaq, anaFaqEntity);
	}
	
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}