/*
 * Created on 9 gen 2023 ( Time 14:26:24 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.whitepaper.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import org.whitepaper.bean.CatMessaggio;
import org.whitepaper.bean.jpa.CatMessaggioEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class CatMessaggioServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public CatMessaggioServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'CatMessaggioEntity' to 'CatMessaggio'
	 * @param catMessaggioEntity
	 */
	public CatMessaggio mapCatMessaggioEntityToCatMessaggio(CatMessaggioEntity catMessaggioEntity) {
		if(catMessaggioEntity == null) {
			return null;
		}

		//--- Generic mapping 
		CatMessaggio catMessaggio = map(catMessaggioEntity, CatMessaggio.class);

		return catMessaggio;
	}
	
	/**
	 * Mapping from 'CatMessaggio' to 'CatMessaggioEntity'
	 * @param catMessaggio
	 * @param catMessaggioEntity
	 */
	public void mapCatMessaggioToCatMessaggioEntity(CatMessaggio catMessaggio, CatMessaggioEntity catMessaggioEntity) {
		if(catMessaggio == null) {
			return;
		}

		//--- Generic mapping 
		map(catMessaggio, catMessaggioEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}