/*
 * Created on 22 nov 2022 ( Time 14:08:09 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.whitepaper.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import org.whitepaper.bean.MessaggioStat;
import org.whitepaper.bean.jpa.MessaggioStatEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class MessaggioStatServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public MessaggioStatServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	
	public MessaggioStat mapMessaggioEntityToMessaggio(MessaggioStatEntity messaggioStatEntity) {
		if(messaggioStatEntity == null) {
			return null;
		}

		//--- Generic mapping 
		MessaggioStat messaggio = map(messaggioStatEntity, MessaggioStat.class);

		return messaggio;
	}
	
	/**
	 * Mapping from 'Messaggio' to 'MessaggioEntity'
	 * @param messaggio
	 * @param messaggioEntity
	 */
	public void mapMessaggioStatToMessaggioStatEntity(MessaggioStat messaggioStat, MessaggioStatEntity messaggioStatEntity) {
		if(messaggioStat == null) {
			return;
		}

		//--- Generic mapping 
		map(messaggioStat, messaggioStatEntity);

	}
	

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}