/*
 * Created on 2022-11-03 ( Time 15:15:46 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
package org.whitepaper.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import org.whitepaper.bean.TipProfilo;
import org.whitepaper.bean.jpa.TipProfiloEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class TipProfiloServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public TipProfiloServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'TipProfiloEntity' to 'TipProfilo'
	 * @param tipProfiloEntity
	 */
	public TipProfilo mapTipProfiloEntityToTipProfilo(TipProfiloEntity tipProfiloEntity) {
		if(tipProfiloEntity == null) {
			return null;
		}

		//--- Generic mapping 
		TipProfilo tipProfilo = map(tipProfiloEntity, TipProfilo.class);

		return tipProfilo;
	}
	
	/**
	 * Mapping from 'TipProfilo' to 'TipProfiloEntity'
	 * @param tipProfilo
	 * @param tipProfiloEntity
	 */
	public void mapTipProfiloToTipProfiloEntity(TipProfilo tipProfilo, TipProfiloEntity tipProfiloEntity) {
		if(tipProfilo == null) {
			return;
		}

		//--- Generic mapping 
		map(tipProfilo, tipProfiloEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}