/*
 * Created on 22 nov 2022 ( Time 14:08:09 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.whitepaper.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import org.whitepaper.bean.UtenteAction;
import org.whitepaper.bean.jpa.UtenteActionEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class UtenteActionServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public UtenteActionServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	
	public UtenteAction mapMessaggioEntityToMessaggio(UtenteActionEntity utenteActionEntity) {
		if(utenteActionEntity == null) {
			return null;
		}

		//--- Generic mapping 
		UtenteAction messaggio = map(utenteActionEntity, UtenteAction.class);

		return messaggio;
	}
	
	/**
	 * Mapping from 'Messaggio' to 'MessaggioEntity'
	 * @param messaggio
	 * @param messaggioEntity
	 */
	public void mapMessaggioStatToMessaggioStatEntity(UtenteAction utenteAction, UtenteActionEntity utenteActiontEntity) {
		if(utenteAction == null) {
			return;
		}

		//--- Generic mapping 
		map(utenteAction, utenteActiontEntity);

	}
	

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}