/*
 * Created on 9 gen 2023 ( Time 14:26:03 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package org.whitepaper.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Persistent class for entity stored in table "cat_messaggio"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="cat_messaggio", catalog="fogliobianco" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="CatMessaggioEntity.countAll", query="SELECT COUNT(x) FROM CatMessaggioEntity x" )
} )
public class CatMessaggioEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name="cat_msg", nullable=false, length=10)
    private String     catMsg       ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="des_cat_msg", length=100)
    private String     desCatMsg    ;

    @Column(name="color_cat", length=10)
    private String colorCat;


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @OneToMany(mappedBy="catMessaggio", targetEntity=MessaggioAdminEntity.class)
    private List<MessaggioAdminEntity> listOfMessaggioAdmin;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public CatMessaggioEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setCatMsg( String catMsg ) {
        this.catMsg = catMsg ;
    }
    public String getCatMsg() {
        return this.catMsg;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : des_cat_msg ( VARCHAR ) 
    public void setDesCatMsg( String desCatMsg ) {
        this.desCatMsg = desCatMsg;
    }
    public String getDesCatMsg() {
        return this.desCatMsg;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setListOfMessaggioAdmin( List<MessaggioAdminEntity> listOfMessaggioAdmin ) {
        this.listOfMessaggioAdmin = listOfMessaggioAdmin;
    }
    public List<MessaggioAdminEntity> getListOfMessaggioAdmin() {
        return this.listOfMessaggioAdmin;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(catMsg);
        sb.append("]:"); 
        sb.append(desCatMsg);
        return sb.toString(); 
    }

	public String getColorCat() {
		return colorCat;
	}

	public void setColorCat(String colorCat) {
		this.colorCat = colorCat;
	} 

    
}
