/*
 * Created on 22 nov 2022 ( Time 14:07:40 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.whitepaper.web.controller;

import java.util.LinkedList;
import java.util.List;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;
import org.whitepaper.bean.AnaUtente;
import org.whitepaper.bean.Messaggio;
import org.whitepaper.bean.TipMessaggio;
import org.whitepaper.business.service.AnaUtenteService;
import org.whitepaper.business.service.MessaggioService;
import org.whitepaper.business.service.TipMessaggioService;
import org.whitepaper.business.service.custom.MessaggioCustomService;
import org.whitepaper.utility.ConstantsDefinition;
import org.whitepaper.web.common.AbstractController;
import org.whitepaper.web.common.FormMode;
import org.whitepaper.web.common.Message;
import org.whitepaper.web.common.MessageType;
import org.whitepaper.web.listitem.AnaUtenteListItem;
import org.whitepaper.web.listitem.TipMessaggioListItem;

/**
 * Spring MVC controller for 'Messaggio' management.
 */
@Controller
@RequestMapping("/messaggio")
public class MessaggioController extends AbstractController {

	//--- Variables names ( to be used in JSP with Expression Language )
	private static final String MAIN_ENTITY_NAME = "messaggio";
	private static final String MAIN_LIST_NAME   = "list";

	//--- JSP pages names ( View name in the MVC model )
	private static final String JSP_FORM   = "messaggio/form";
	private static final String JSP_LIST   = "messaggio/list";

	//--- SAVE ACTION ( in the HTML form )
	private static final String SAVE_ACTION_CREATE   = "/messaggio/create";
	private static final String SAVE_ACTION_UPDATE   = "/messaggio/update";

	//--- Main entity service
	@Resource
    private MessaggioService messaggioService; // Injected by Spring
	
	@Resource
    private MessaggioCustomService messaggioCustomService;
	//--- Other service(s)
	@Resource
    private AnaUtenteService anaUtenteService; // Injected by Spring
	@Resource
    private TipMessaggioService tipMessaggioService; // Injected by Spring

	//--------------------------------------------------------------------------------------
	/**
	 * Default constructor
	 */
	public MessaggioController() {
		super(MessaggioController.class, MAIN_ENTITY_NAME );
		log("MessaggioController created.");
	}

	//--------------------------------------------------------------------------------------
	// Spring MVC model management
	//--------------------------------------------------------------------------------------
	/**
	 * Populates the combo-box "items" for the referenced entity "AnaUtente"
	 * @param model
	 */
	private void populateListOfAnaUtenteItems(Model model) {
		List<AnaUtente> list = anaUtenteService.findAll();
		List<AnaUtenteListItem> items = new LinkedList<AnaUtenteListItem>();
		for ( AnaUtente anaUtente : list ) {
			items.add(new AnaUtenteListItem( anaUtente ) );
		}
		model.addAttribute("listOfAnaUtenteItems", items ) ;
	}

	/**
	 * Populates the combo-box "items" for the referenced entity "TipMessaggio"
	 * @param model
	 */
	private void populateListOfTipMessaggioItems(Model model) {
		List<TipMessaggio> list = tipMessaggioService.findAll();
		List<TipMessaggioListItem> items = new LinkedList<TipMessaggioListItem>();
		for ( TipMessaggio tipMessaggio : list ) {
			items.add(new TipMessaggioListItem( tipMessaggio ) );
		}
		model.addAttribute("listOfTipMessaggioItems", items ) ;
	}


	/**
	 * Populates the Spring MVC model with the given entity and eventually other useful data
	 * @param model
	 * @param messaggio
	 */
	private void populateModel(Model model, Messaggio messaggio, FormMode formMode) {
		//--- Main entity
		model.addAttribute(MAIN_ENTITY_NAME, messaggio);
		if ( formMode == FormMode.CREATE ) {
			model.addAttribute(MODE, MODE_CREATE); // The form is in "create" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_CREATE); 			
			//--- Other data useful in this screen in "create" mode (all fields)
			populateListOfAnaUtenteItems(model);
			populateListOfTipMessaggioItems(model);
		}
		else if ( formMode == FormMode.UPDATE ) {
			model.addAttribute(MODE, MODE_UPDATE); // The form is in "update" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_UPDATE); 			
			//--- Other data useful in this screen in "update" mode (only non-pk fields)
			populateListOfAnaUtenteItems(model);
			populateListOfTipMessaggioItems(model);
		}
	}

	//--------------------------------------------------------------------------------------
	// Request mapping
	//--------------------------------------------------------------------------------------
	/**
	 * Shows a list with all the occurrences of Messaggio found in the database
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping()
	public String list(Model model) {
		log("Action 'list'");
		List<Messaggio> list = messaggioService.findAll();
		model.addAttribute(MAIN_LIST_NAME, list);		
		return JSP_LIST;
	}

	/**
	 * Shows a form page in order to create a new Messaggio
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping("/form")
	public String formForCreate(Model model) {
		log("Action 'formForCreate'");
		//--- Populates the model with a new instance
		Messaggio messaggio = new Messaggio();	
		populateModel( model, messaggio, FormMode.CREATE);
		return JSP_FORM;
	}

	/**
	 * Shows a form page in order to update an existing Messaggio
	 * @param model Spring MVC model
	 * @param idMsg  primary key element
	 * @return
	 */
	@RequestMapping(value = "/form/{idMsg}")
	public String formForUpdate(Model model, @PathVariable("idMsg") Integer idMsg ) {
		log("Action 'formForUpdate'");
		//--- Search the entity by its primary key and stores it in the model 
		Messaggio messaggio = messaggioService.findById(idMsg);
		populateModel( model, messaggio, FormMode.UPDATE);		
		return JSP_FORM;
	}

	/**
	 * 'CREATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param messaggio  entity to be created
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/create" ) // GET or POST
	public String create(Messaggio messaggio, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'create'");
		try {
			if (!bindingResult.hasErrors()) {
				Messaggio messaggioCreated = messaggioService.create(messaggio); 
				model.addAttribute(MAIN_ENTITY_NAME, messaggioCreated);

				//---
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				return redirectToForm(httpServletRequest, messaggioCreated.getIdMsg() );
			} else {
				populateModel( model, messaggio, FormMode.CREATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			log("Action 'create' : Exception - " + e.getMessage() );
			messageHelper.addException(model, "messaggio.error.create", e);
			populateModel( model, messaggio, FormMode.CREATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'UPDATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param messaggio  entity to be updated
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/update" ) // GET or POST
	public String update(Messaggio messaggio, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'update'");
		try {
			if (!bindingResult.hasErrors()) {
				//--- Perform database operations
				Messaggio messaggioSaved = messaggioService.update(messaggio);
				model.addAttribute(MAIN_ENTITY_NAME, messaggioSaved);
				//--- Set the result message
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				log("Action 'update' : update done - redirect");
				return redirectToForm(httpServletRequest, messaggioSaved.getIdMsg());
			} else {
				log("Action 'update' : binding errors");
				populateModel( model, messaggio, FormMode.UPDATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			messageHelper.addException(model, "messaggio.error.update", e);
			log("Action 'update' : Exception - " + e.getMessage() );
			populateModel( model, messaggio, FormMode.UPDATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'DELETE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param redirectAttributes
	 * @param idMsg  primary key element
	 * @return
	 */
	@RequestMapping(value = "/delete/{idMsg}") // GET or POST
	public String delete(RedirectAttributes redirectAttributes, @PathVariable("idMsg") Integer idMsg) {
		log("Action 'delete'" );
		try {
			messaggioService.delete( idMsg );
			//--- Set the result message
			messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"delete.ok"));	
		} catch(Exception e) {
			messageHelper.addException(redirectAttributes, "messaggio.error.delete", e);
		}
		return redirectToList();
	}
	
	@RequestMapping(value = "/messaggicco", method = RequestMethod.GET) // GET or POST
	public String listMessaggiCCO(Model model) {
		log("Action 'listMessaggiCCO'");
		//--- Populates the model with a new instance		
		List<Messaggio> list = messaggioCustomService.findMsgPerCodTipMsg(ConstantsDefinition.CODMSG_CCO);
		model.addAttribute(MAIN_LIST_NAME, list);			
		return JSP_LIST;
	}

}
