/*
 * Created on 2022-11-03 ( Time 15:16:05 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
// This Bean has a basic Primary Key (not composite) 

package org.whitepaper.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.List;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "tip_messaggio"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="tip_messaggio", catalog="fogliobianco" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="TipMessaggioEntity.countAll", query="SELECT COUNT(x) FROM TipMessaggioEntity x" )
} )
public class TipMessaggioEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name="cod_tip_msg", nullable=false, length=10)
    private String     codTipMsg    ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="des_tip_msg", length=100)
    private String     desTipMsg    ;

    @Column(name="color_tip", length=10)
    private String     colorTip    ;


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @OneToMany(mappedBy="tipMessaggio", targetEntity=MessaggioEntity.class)
    private List<MessaggioEntity> listOfMessaggio;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public TipMessaggioEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setCodTipMsg( String codTipMsg ) {
        this.codTipMsg = codTipMsg ;
    }
    public String getCodTipMsg() {
        return this.codTipMsg;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : des_tip_msg ( VARCHAR ) 
    public void setDesTipMsg( String desTipMsg ) {
        this.desTipMsg = desTipMsg;
    }
    public String getDesTipMsg() {
        return this.desTipMsg;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setListOfMessaggio( List<MessaggioEntity> listOfMessaggio ) {
        this.listOfMessaggio = listOfMessaggio;
    }
    public List<MessaggioEntity> getListOfMessaggio() {
        return this.listOfMessaggio;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(codTipMsg);
        sb.append("]:"); 
        sb.append(desTipMsg);
        return sb.toString(); 
    }

	public String getColorTip() {
		return colorTip;
	}

	public void setColorTip(String colorTip) {
		this.colorTip = colorTip;
	} 

    
}
