/*
 * Created on 17 mag 2018 ( Time 10:04:04 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.whitepaper.bean;

import java.io.Serializable;
import java.util.Date;

public class AnaFaq implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer idFaq;
    private String domFaq;
    private String risFaq;
    private Date datFaq;
    private String codStaFaq;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setIdFaq( Integer idFaq ) {
        this.idFaq = idFaq ;
    }

    public Integer getIdFaq() {
        return this.idFaq;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setDomFaq( String domFaq ) {
        this.domFaq = domFaq;
    }
    public String getDomFaq() {
        return this.domFaq;
    }

    public void setRisFaq( String risFaq ) {
        this.risFaq = risFaq;
    }
    public String getRisFaq() {
        return this.risFaq;
    }

    public void setDatFaq( Date datFaq ) {
        this.datFaq = datFaq;
    }
    public Date getDatFaq() {
        return this.datFaq;
    }

	public String getCodStaFaq() {
		return codStaFaq;
	}

	public void setCodStaFaq(String codStaFaq) {
		this.codStaFaq = codStaFaq;
	}



}
