/*
 * Created on 2022-11-03 ( Time 15:19:50 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
package org.whitepaper.bean;

import java.io.Serializable;
import java.util.Date;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

public class AnaUtente implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Integer idUte;

    private String username;
    
    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @NotNull
    @Size( min = 1, max = 250 )
    private String email;
    private String emailConf;

    @NotNull
    @Size( min = 1, max = 60 )
    private String pwd;
    private String pwdConf;
    private String pwdNew;

    private Date datCreUte;

    @Size( max = 45 )
    private String conUid;

    @NotNull
    @Size( min = 1, max = 10 )
    private String codTipPrf;
    private String desTipPrf;

    @NotNull
    private Date datUltMov;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setIdUte( Integer idUte ) {
        this.idUte = idUte ;
    }

    public Integer getIdUte() {
        return this.idUte;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setEmail( String email ) {
        this.email = email;
    }
    public String getEmail() {
        return this.email;
    }

    public void setPwd( String pwd ) {
        this.pwd = pwd;
    }
    public String getPwd() {
        return this.pwd;
    }

    public void setDatCreUte( Date datCreUte ) {
        this.datCreUte = datCreUte;
    }
    public Date getDatCreUte() {
        return this.datCreUte;
    }

    public void setConUid( String conUid ) {
        this.conUid = conUid;
    }
    public String getConUid() {
        return this.conUid;
    }

    public void setCodTipPrf( String codTipPrf ) {
        this.codTipPrf = codTipPrf;
    }
    public String getCodTipPrf() {
        return this.codTipPrf;
    }

    public void setDatUltMov( Date datUltMov ) {
        this.datUltMov = datUltMov;
    }
    public Date getDatUltMov() {
        return this.datUltMov;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idUte);
        sb.append("|");
        sb.append(email);
        sb.append("|");
        sb.append(codTipPrf);
        sb.append("|");        
        return sb.toString(); 
    }

		public String getUsername() {
			return username;
		}

		public void setUsername(String username) {
			this.username = username;
		}

		public String getDesTipPrf() {
			return desTipPrf;
		}

		public void setDesTipPrf(String desTipPrf) {
			this.desTipPrf = desTipPrf;
		}

		public String getEmailConf() {
			return emailConf;
		}

		public void setEmailConf(String emailConf) {
			this.emailConf = emailConf;
		}

		public String getPwdConf() {
			return pwdConf;
		}

		public void setPwdConf(String pwdConf) {
			this.pwdConf = pwdConf;
		}

		public String getPwdNew() {
			return pwdNew;
		}

		public void setPwdNew(String pwdNew) {
			this.pwdNew = pwdNew;
		} 
        
}
