/*
 * Created on 9 gen 2023 ( Time 14:25:41 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.whitepaper.bean;

import java.io.Serializable;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


public class CatMessaggio implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    @Size( min = 1, max = 10 )
    private String catMsg;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Size( max = 100 )
    private String desCatMsg;

    @Size( max = 10 )
    private String colorCat;


    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setCatMsg( String catMsg ) {
        this.catMsg = catMsg ;
    }

    public String getCatMsg() {
        return this.catMsg;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setDesCatMsg( String desCatMsg ) {
        this.desCatMsg = desCatMsg;
    }
    public String getDesCatMsg() {
        return this.desCatMsg;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(catMsg);
        sb.append("|");
        sb.append(desCatMsg);
        return sb.toString(); 
    }

		public String getColorCat() {
			return colorCat;
		}

		public void setColorCat(String colorCat) {
			this.colorCat = colorCat;
		} 


        
}
