/*
 * Created on 22 nov 2022 ( Time 14:07:40 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.whitepaper.bean;

import java.io.Serializable;

public class FoglioIndice implements Serializable {

    private static final long serialVersionUID = 1L;

    private int idFoglio;
    private boolean presenteRisposta;
    
    //per evindenziare foglio con risposta da inviare
    private boolean	sendReply;
    
    
	public int getIdFoglio() {
		return idFoglio;
	}
	public void setIdFoglio(int idFoglio) {
		this.idFoglio = idFoglio;
	}
	public boolean isPresenteRisposta() {
		return presenteRisposta;
	}
	public void setPresenteRisposta(boolean presenteRisposta) {
		this.presenteRisposta = presenteRisposta;
	}
	public boolean isSendReply() {
		return sendReply;
	}
	public void setSendReply(boolean sendReply) {
		this.sendReply = sendReply;
	}
    
	

    
}