/*
 * Created on 2022-11-03 ( Time 15:20:00 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
package org.whitepaper.bean;

import java.io.Serializable;

import javax.validation.constraints.*;

import java.util.Date;

public class MessaggioTags implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Integer idTag;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @NotNull
    private Integer idMsg;

    @NotNull
    @Size( min = 1, max = 50 )
    private String tag;


    private Date datUltMov;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setIdTag( Integer idTag ) {
        this.idTag = idTag ;
    }

    public Integer getIdTag() {
        return this.idTag;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setIdMsg( Integer idMsg ) {
        this.idMsg = idMsg;
    }
    public Integer getIdMsg() {
        return this.idMsg;
    }

    public void setTag( String tag ) {
        this.tag = tag;
    }
    public String getTag() {
        return this.tag;
    }

    public void setDatUltMov( Date datUltMov ) {
        this.datUltMov = datUltMov;
    }
    public Date getDatUltMov() {
        return this.datUltMov;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idTag);
        sb.append("|");
        sb.append(idMsg);
        sb.append("|");
        sb.append(tag);
        sb.append("|");
        sb.append(datUltMov);
        return sb.toString(); 
    } 


}
