/*
 * Created on 19 gen 2023 ( Time 08:35:16 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.whitepaper.bean;

import java.io.Serializable;

import javax.validation.constraints.*;

import java.util.Date;

public class MessaggioSegnalato implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Integer idMsgSegn;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @NotNull
    private Integer idMsg;
    private String  desMsg;

    @Size( max = 250 )
    private String desMot;

    @NotNull
    private Date datSegn;

    @NotNull
    private Date datUltMov;

    @NotNull
    private Integer idUteSegn;
    private String  emailUteAut;
    private String  emailUteSegn;

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setIdMsgSegn( Integer idMsgSegn ) {
        this.idMsgSegn = idMsgSegn ;
    }

    public Integer getIdMsgSegn() {
        return this.idMsgSegn;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setIdMsg( Integer idMsg ) {
        this.idMsg = idMsg;
    }
    public Integer getIdMsg() {
        return this.idMsg;
    }

    public void setDesMot( String desMot ) {
        this.desMot = desMot;
    }
    public String getDesMot() {
        return this.desMot;
    }

    public void setDatSegn( Date datSegn ) {
        this.datSegn = datSegn;
    }
    public Date getDatSegn() {
        return this.datSegn;
    }

    public void setDatUltMov( Date datUltMov ) {
        this.datUltMov = datUltMov;
    }
    public Date getDatUltMov() {
        return this.datUltMov;
    }

    public void setIdUteSegn( Integer idUteSegn ) {
        this.idUteSegn = idUteSegn;
    }
    public Integer getIdUteSegn() {
        return this.idUteSegn;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idMsgSegn);
        sb.append("|");
        sb.append(idMsg);
        sb.append("|");
        sb.append(desMot);
        sb.append("|");
        sb.append(datSegn);
        sb.append("|");
        sb.append(datUltMov);
        sb.append("|");
        sb.append(idUteSegn);
        return sb.toString(); 
    }

		public String getEmailUteSegn() {
			return emailUteSegn;
		}

		public void setEmailUteSegn(String emailUteSegn) {
			this.emailUteSegn = emailUteSegn;
		}

		public String getDesMsg() {
			return desMsg;
		}

		public void setDesMsg(String desMsg) {
			this.desMsg = desMsg;
		}

		public String getEmailUteAut() {
			return emailUteAut;
		}

		public void setEmailUteAut(String emailUteAut) {
			this.emailUteAut = emailUteAut;
		} 


        
}
