/*
* Created on 22 nov 2022 ( Time 14:07:40 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.whitepaper.bean;

import java.io.Serializable;
import java.util.Date;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.whitepaper.utility.ConstantsDefinition;
import org.whitepaper.utility.UtilityFunction;

public class Messaggio implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Integer idMsg;
        
    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Size( max = 1000 )
    private String desMsg;
    private String titMsg;

    private Integer idUteAut;
    private String	emailAut;

    private Integer idUteReply;
    private Integer idMsgReply;

    @Size( max = 10 )
    private String codTipMsg;
    private String desTipMsg;
    private boolean tipMsgPub;
    private boolean tipMsgPri;
    

    @NotNull
    private Date datUltMov;
    private String datUltMovView;
    
    //data pubblicazione del messaggio
    private Date       dataPub;
    
    @NotNull
    private Integer    idFoglio;
    private Integer    idFoglioOrig;

    private boolean	segnala = false;
    private boolean	presenteRisposta;
    
    
    private String hashtag;
    private String desErrHashTag;
    private String desSuccessHashTag;
    
    //motivazione segnalazione messaggio offensivo
    private String desMot;
    private boolean offensivo;
    
    //indica se l'autore del messaggio is utente registrato
    private boolean msgUteReg;
    
    private boolean foundMsgPubRandom = true;;
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setIdMsg( Integer idMsg ) {
        this.idMsg = idMsg ;
    }

    public Integer getIdMsg() {
        return this.idMsg;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setDesMsg( String desMsg ) {
        this.desMsg = desMsg;
    }
    public String getDesMsg() {
    	if ( null==this.desMsg || this.desMsg.isEmpty() )
    		return this.desMsg;
    			
    	//check new line
    	setDesMsg( this.desMsg.replaceAll("(\r\n|\n)", "<br />").trim());
        return this.desMsg;
    }

    public void setIdUteAut( Integer idUteAut ) {
        this.idUteAut = idUteAut;
    }
    public Integer getIdUteAut() {
        return this.idUteAut;
    }

    public void setIdUteReply( Integer idUteReply ) {
        this.idUteReply = idUteReply;
    }
    public Integer getIdUteReply() {
        return this.idUteReply;
    }

    public void setCodTipMsg( String codTipMsg ) {
        this.codTipMsg = codTipMsg;
    }
    public String getCodTipMsg() {
        return this.codTipMsg;
    }

    public void setDatUltMov( Date datUltMov ) {
        this.datUltMov = datUltMov;
    }
    public Date getDatUltMov() {
        return this.datUltMov;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idMsg);
        sb.append("|");
        sb.append(desMsg);
        sb.append("|");
        sb.append(idUteAut);
        sb.append("|");
        sb.append(idUteReply);
        sb.append("|");
        sb.append(codTipMsg);
        sb.append("|");
        sb.append(datUltMov);
        return sb.toString(); 
    } 

	public String getDatUltMovView() {    	
        return UtilityFunction.getDataView(datUltMov, "dd MMMM yyyy HH:mm");	        
    }
	

	public Integer getIdFoglio() {
		return idFoglio;
	}

	public void setIdFoglio(Integer idFoglio) {
		this.idFoglio = idFoglio;
	}

	public String getTitMsg() {
		return titMsg;
	}

	public void setTitMsg(String titMsg) {
		this.titMsg = titMsg;
	}

	public Integer getIdMsgReply() {
		return idMsgReply;
	}

	public void setIdMsgReply(Integer idMsgReply) {
		this.idMsgReply = idMsgReply;
	}

	public Integer getIdFoglioOrig() {
		return idFoglioOrig;
	}

	public void setIdFoglioOrig(Integer idFoglioOrig) {
		this.idFoglioOrig = idFoglioOrig;
	}

	public boolean isPresenteRisposta() {
		return presenteRisposta;
	}

	public void setPresenteRisposta(boolean presenteRisposta) {
		this.presenteRisposta = presenteRisposta;
	}

	public boolean isSegnala() {
		return segnala;
	}

	public void setSegnala(boolean segnala) {
		this.segnala = segnala;
	}

	public String getDesTipMsg() {
		return desTipMsg;
	}

	public void setDesTipMsg(String desTipMsg) {
		this.desTipMsg = desTipMsg;
	}

	public String getEmailAut() {
		return emailAut;
	}

	public void setEmailAut(String emailAut) {
		this.emailAut = emailAut;
	}

	public String getHashtag() {
		return hashtag;
	}

	public void setHashtag(String hashtag) {
		this.hashtag = hashtag;
	}

	public String getDesErrHashTag() {
		return desErrHashTag;
	}

	public void setDesErrHashTag(String desErrHashTag) {
		this.desErrHashTag = desErrHashTag;
	}

	public String getDesSuccessHashTag() {
		return desSuccessHashTag;
	}

	public void setDesSuccessHashTag(String desSuccessHashTag) {
		this.desSuccessHashTag = desSuccessHashTag;
	}

	public String getDesMot() {
		return desMot;
	}

	public void setDesMot(String desMot) {
		this.desMot = desMot;
	}

	public boolean isOffensivo() {
		
		if ( null==codTipMsg || codTipMsg.isEmpty() )
			return false;
		
		if ( !codTipMsg.equals(ConstantsDefinition.CODMSG_CCO) )
			return false;
		
		return true;
	}

	public boolean isMsgUteReg() {
		return msgUteReg;
	}

	public void setMsgUteReg(boolean msgUteReg) {
		this.msgUteReg = msgUteReg;
	}

	public Date getDataPub() {
		return dataPub;
	}

	public void setDataPub(Date dataPub) {
		this.dataPub = dataPub;
	}

	public boolean isFoundMsgPubRandom() {
		return foundMsgPubRandom;
	}

	public void setFoundMsgPubRandom(boolean foundMsgPubRandom) {
		this.foundMsgPubRandom = foundMsgPubRandom;
	}

	public boolean isTipMsgPub() {
		
		if ( this.getCodTipMsg()!=null && this.getCodTipMsg().equals(ConstantsDefinition.CODMSG_PUB)) 			
			 return true;
			
		return false;
	}

	public void setTipMsgPub(boolean tipMsgPub) {
		this.tipMsgPub = tipMsgPub;
	}

	public boolean isTipMsgPri() {
		
		if ( this.getCodTipMsg()!=null && this.getCodTipMsg().equals(ConstantsDefinition.CODMSG_PRI)) 			
			 return true;
			
		return false;		
	}

	public void setTipMsgPri(boolean tipMsgPri) {
		this.tipMsgPri = tipMsgPri;
	}


	
	
	
}