/*
 * Created on 9 gen 2023 ( Time 14:25:41 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.whitepaper.bean;

import java.io.Serializable;
import java.util.Date;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

public class MessaggioAdmin implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Integer idMsg;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @NotNull
    @Size( min = 1, max = 500 )
    private String desMsg;
    private String titMsg;

    @Size( max = 10 )
    private String codTipMsg;
    private String desTipMsg;
    private String desCatMsg;

    private Date datUltMov;

    @Size( max = 10 )
    private String catMsg;


    private Date datInizioVal;


    private Date datFineVal;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setIdMsg( Integer idMsg ) {
        this.idMsg = idMsg ;
    }

    public Integer getIdMsg() {
        return this.idMsg;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setDesMsg( String desMsg ) {
        this.desMsg = desMsg;
    }
    public String getDesMsg() {
        return this.desMsg;
    }

    public void setCodTipMsg( String codTipMsg ) {
        this.codTipMsg = codTipMsg;
    }
    public String getCodTipMsg() {
        return this.codTipMsg;
    }

    public void setDatUltMov( Date datUltMov ) {
        this.datUltMov = datUltMov;
    }
    public Date getDatUltMov() {
        return this.datUltMov;
    }

    public void setCatMsg( String catMsg ) {
        this.catMsg = catMsg;
    }
    public String getCatMsg() {
        return this.catMsg;
    }

    public void setDatInizioVal( Date datInizioVal ) {
        this.datInizioVal = datInizioVal;
    }
    public Date getDatInizioVal() {
        return this.datInizioVal;
    }

    public void setDatFineVal( Date datFineVal ) {
        this.datFineVal = datFineVal;
    }
    public Date getDatFineVal() {
        return this.datFineVal;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idMsg);
        sb.append("|");
        sb.append(desMsg);
        sb.append("|");
        sb.append(codTipMsg);
        sb.append("|");
        sb.append(datUltMov);
        sb.append("|");
        sb.append(catMsg);
        sb.append("|");
        sb.append(datInizioVal);
        sb.append("|");
        sb.append(datFineVal);
        return sb.toString(); 
    }

		public String getDesTipMsg() {
			return desTipMsg;
		}

		public void setDesTipMsg(String desTipMsg) {
			this.desTipMsg = desTipMsg;
		}

		public String getDesCatMsg() {
			return desCatMsg;
		}

		public void setDesCatMsg(String desCatMsg) {
			this.desCatMsg = desCatMsg;
		}

		public String getTitMsg() {
			return titMsg;
		}

		public void setTitMsg(String titMsg) {
			this.titMsg = titMsg;
		} 

        

}
