/*
 * Created on 2022-11-03 ( Time 15:20:01 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
package org.whitepaper.bean;

import java.io.Serializable;

import javax.validation.constraints.*;


public class TipMessaggio implements Serializable {

    private static final long serialVersionUID = 1L;
    
    public TipMessaggio() {}
    
    public TipMessaggio(String codTipMsg, String desTipMsg) {
		this.setCodTipMsg(codTipMsg);
		this.setDesTipMsg(desTipMsg);
	}

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    @Size( min = 1, max = 10 )
    private String codTipMsg;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Size( max = 100 )
    private String desTipMsg;

    @Size( max = 10 )
    private String    colorTip    ;

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setCodTipMsg( String codTipMsg ) {
        this.codTipMsg = codTipMsg ;
    }

    public String getCodTipMsg() {
        return this.codTipMsg;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setDesTipMsg( String desTipMsg ) {
        this.desTipMsg = desTipMsg;
    }
    public String getDesTipMsg() {
        return this.desTipMsg;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(codTipMsg);
        sb.append("|");
        sb.append(desTipMsg);
        return sb.toString(); 
    }

		public String getColorTip() {
			return colorTip;
		}

		public void setColorTip(String colorTip) {
			this.colorTip = colorTip;
		} 

        

}
