/*
 * Created on 2022-11-03 ( Time 15:20:01 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
package org.whitepaper.bean;

import java.io.Serializable;

import javax.validation.constraints.*;


public class TipProfilo implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    @Size( min = 1, max = 10 )
    private String codTipPrf;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Size( max = 100 )
    private String desTipPrf;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setCodTipPrf( String codTipPrf ) {
        this.codTipPrf = codTipPrf ;
    }

    public String getCodTipPrf() {
        return this.codTipPrf;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setDesTipPrf( String desTipPrf ) {
        this.desTipPrf = desTipPrf;
    }
    public String getDesTipPrf() {
        return this.desTipPrf;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(codTipPrf);
        sb.append("|");
        sb.append(desTipPrf);
        return sb.toString(); 
    } 


}
