/*
 * Created on 31 gen 2023 ( Time 08:05:09 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.whitepaper.web.listitem;

import org.whitepaper.bean.Faq;
import org.whitepaper.web.common.ListItem;

public class FaqListItem implements ListItem {

	private final String value ;
	private final String label ;
	
	public FaqListItem(Faq faq) {
		super();

		this.value = ""
			 + faq.getIdFaq()
		;

		//TODO : Define here the attributes to be displayed as the label
		this.label = faq.toString();
	}

	@Override
	public String getValue() {
		return value;
	}

	@Override
	public String getLabel() {
		return label;
	}

}
