/*
 * Created on 13 lug 2017 ( Time 12:07:28 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.whitepaper.business.service.custom;


import org.whitepaper.bean.AnaUtente;

/**
 * Business Service Interface for entity AnaUtente.
 */
public interface GestUtenteService { 

	
	String confermaUtente(AnaUtente anaUtente);
	String checkUsernameMail(String email);	
	AnaUtente insertUtente(AnaUtente anaUtente, String linkConferma) throws Exception;
	
	AnaUtente findUtenteByConUid(String conUid);				
	AnaUtente findUtentePerIdUte(Integer idUte);	
	AnaUtente findUtenteByMail(String mail);
		
	AnaUtente updatePassword(AnaUtente anaUtente);	 
	AnaUtente updateUserNoPassword(AnaUtente anaUtente);
	AnaUtente updateRecuperoPassword(AnaUtente anaUtente, String linkRecupero);	
	AnaUtente updatePasswordByLinkRecupero(AnaUtente anaUtente) ;
	
	long countUtentiPerCodPrf(String codTipPrf);
	
	 
}
