/*
 * Created on 2022-11-03 ( Time 15:15:46 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
package org.whitepaper.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import org.whitepaper.bean.MessaggioTags;
import org.whitepaper.bean.jpa.MessaggioTagsEntity;
import org.whitepaper.bean.jpa.MessaggioEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class MessaggioTagsServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public MessaggioTagsServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'MessaggioTagsEntity' to 'MessaggioTags'
	 * @param messaggioTagsEntity
	 */
	public MessaggioTags mapMessaggioTagsEntityToMessaggioTags(MessaggioTagsEntity messaggioTagsEntity) {
		if(messaggioTagsEntity == null) {
			return null;
		}

		//--- Generic mapping 
		MessaggioTags messaggioTags = map(messaggioTagsEntity, MessaggioTags.class);

		//--- Link mapping ( link to Messaggio )
		if(messaggioTagsEntity.getMessaggio() != null) {
			messaggioTags.setIdMsg(messaggioTagsEntity.getMessaggio().getIdMsg());
		}
		return messaggioTags;
	}
	
	/**
	 * Mapping from 'MessaggioTags' to 'MessaggioTagsEntity'
	 * @param messaggioTags
	 * @param messaggioTagsEntity
	 */
	public void mapMessaggioTagsToMessaggioTagsEntity(MessaggioTags messaggioTags, MessaggioTagsEntity messaggioTagsEntity) {
		if(messaggioTags == null) {
			return;
		}

		//--- Generic mapping 
		map(messaggioTags, messaggioTagsEntity);

		//--- Link mapping ( link : messaggioTags )
		if( hasLinkToMessaggio(messaggioTags) ) {
			MessaggioEntity messaggio1 = new MessaggioEntity();
			messaggio1.setIdMsg( messaggioTags.getIdMsg() );
			messaggioTagsEntity.setMessaggio( messaggio1 );
		} else {
			messaggioTagsEntity.setMessaggio( null );
		}

	}
	
	/**
	 * Verify that Messaggio id is valid.
	 * @param Messaggio Messaggio
	 * @return boolean
	 */
	private boolean hasLinkToMessaggio(MessaggioTags messaggioTags) {
		if(messaggioTags.getIdMsg() != null) {
			return true;
		}
		return false;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}