name: taipme_mobile
description: "antisocial media"
publish_to: 'none'
version: 0.6.0+4

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  # Translations
  flutter_localizations:
    sdk: flutter
  intl: any

  # Security
  # firebase_app_check: ^0.3.1+3 
  flutter_dotenv: ^5.1.0 

  # Models / Immutability
  freezed_annotation: ^2.4.1 
  json_annotation: ^4.9.0 

  # Controllers / Providers
  riverpod_annotation: ^2.5.3 
  flutter_riverpod: ^2.5.3 

  # Deep Links
  # app_links: ^6.3.3 

  # Utility
  collection: ^1.18.0 

  # Local Storage
  shared_preferences: ^2.3.2 
  flutter_secure_storage: ^9.2.4 

  # HTTP Requests
  http: ^1.2.2 

  # Logo
  flutter_launcher_icons: ^0.14.3 

  # Routing/Navigation
  go_router: ^14.6.3 
  url_launcher: ^6.3.1

  # App Initialization
  another_flutter_splash_screen: ^1.2.1 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.2
  build_runner: ^2.4.13
  riverpod_generator: ^2.6.2
  freezed: ^2.5.7
  json_serializable: ^6.8.0

flutter:
  generate: true
  uses-material-design: true

  assets: 
    - .env
    - assets/
    - assets/logo/
    - assets/fonts/

  fonts:
    - family: JosefinSlab
      fonts:
        - asset: assets/fonts/JosefinSlab-Thin.ttf
          weight: 100
        - asset: assets/fonts/JosefinSlab-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/JosefinSlab-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/JosefinSlab-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/JosefinSlab-Light.ttf
          weight: 300
        - asset: assets/fonts/JosefinSlab-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/JosefinSlab-Regular.ttf
          weight: 400
        - asset: assets/fonts/JosefinSlab-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/JosefinSlab-Medium.ttf
          weight: 500
        - asset: assets/fonts/JosefinSlab-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/JosefinSlab-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/JosefinSlab-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/JosefinSlab-Bold.ttf
          weight: 700

    - family: Lucida
      fonts:
        - asset: assets/fonts/lucon.ttf