/*
 * Created on 17 mag 2018 ( Time 10:03:00 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.whitepaper.business.service;
import java.util.List;

import org.whitepaper.bean.AnaFaq;

/**
 * Business Service Interface for entity AnaFaq.
 */
public interface AnaFaqService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param idFaq
	 * @return entity
	 */
	AnaFaq findById( Integer idFaq  ) ;

	

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<AnaFaq> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	AnaFaq save(AnaFaq entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	AnaFaq update(AnaFaq entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	AnaFaq create(AnaFaq entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param idFaq
	 */
	void delete( Integer idFaq );

	//faq per stato
	List<AnaFaq> loadFaqsPerStato(String codStatFaq);
		

}
