/*
 * Created on 9 gen 2023 ( Time 14:26:24 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.whitepaper.business.service;

import java.util.List;

import org.whitepaper.bean.CatMessaggio;

/**
 * Business Service Interface for entity CatMessaggio.
 */
public interface CatMessaggioService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param catMsg
	 * @return entity
	 */
	CatMessaggio findById( String catMsg  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<CatMessaggio> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	CatMessaggio save(CatMessaggio entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	CatMessaggio update(CatMessaggio entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	CatMessaggio create(CatMessaggio entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param catMsg
	 */
	void delete( String catMsg );


}
