/*
 * Created on 22 nov 2022 ( Time 14:08:09 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.whitepaper.business.service;

import java.util.List;

import org.whitepaper.bean.Messaggio;

/**
 * Business Service Interface for entity Messaggio.
 */
public interface MessaggioService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param idMsg
	 * @return entity
	 */
	Messaggio findById( Integer idMsg  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Messaggio> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Messaggio save(Messaggio entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Messaggio update(Messaggio entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Messaggio create(Messaggio entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param idMsg
	 */
	void delete( Integer idMsg );


}
