/*
 * Created on 19 gen 2023 ( Time 08:35:45 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.whitepaper.business.service;

import java.util.List;

import org.whitepaper.bean.MessaggioSegnalato;

/**
 * Business Service Interface for entity MessaggioSegnalato.
 */
public interface MessaggioSegnalatoService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param idMsgSegn
	 * @return entity
	 */
	MessaggioSegnalato findById( Integer idMsgSegn  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<MessaggioSegnalato> findAll();
	
	long coutAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	MessaggioSegnalato save(MessaggioSegnalato entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	MessaggioSegnalato update(MessaggioSegnalato entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	MessaggioSegnalato create(MessaggioSegnalato entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param idMsgSegn
	 */
	void delete( Integer idMsgSegn );


}
