/*
 * Created on 2023-12-11 ( Time 14:18:11 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
package org.whitepaper.business.service;

import java.util.List;

import org.whitepaper.bean.TipInfo;

/**
 * Business Service Interface for entity TipInfo.
 */
public interface TipInfoService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	TipInfo findById( Integer id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<TipInfo> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	TipInfo save(TipInfo entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	TipInfo update(TipInfo entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	TipInfo create(TipInfo entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );


	String findELementRandom(String codInfo);
}
