/*
 * Created on 2022-11-03 ( Time 15:20:01 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
package org.whitepaper.business.service;

import java.util.List;

import org.whitepaper.bean.TipMessaggio;

/**
 * Business Service Interface for entity TipMessaggio.
 */
public interface TipMessaggioService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param codTipMsg
	 * @return entity
	 */
	TipMessaggio findById( String codTipMsg  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<TipMessaggio> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	TipMessaggio save(TipMessaggio entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	TipMessaggio update(TipMessaggio entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	TipMessaggio create(TipMessaggio entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param codTipMsg
	 */
	void delete( String codTipMsg );


}
