/*
 * Created on 2022-11-03 ( Time 15:20:02 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
package org.whitepaper.business.service;

import java.util.List;

import org.whitepaper.bean.TipProfilo;

/**
 * Business Service Interface for entity TipProfilo.
 */
public interface TipProfiloService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param codTipPrf
	 * @return entity
	 */
	TipProfilo findById( String codTipPrf  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<TipProfilo> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	TipProfilo save(TipProfilo entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	TipProfilo update(TipProfilo entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	TipProfilo create(TipProfilo entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param codTipPrf
	 */
	void delete( String codTipPrf );


}
