/*
 * Created on 2022-11-03 ( Time 15:15:46 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
package org.whitepaper.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import org.whitepaper.bean.TipMessaggio;
import org.whitepaper.bean.jpa.TipMessaggioEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class TipMessaggioServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public TipMessaggioServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'TipMessaggioEntity' to 'TipMessaggio'
	 * @param tipMessaggioEntity
	 */
	public TipMessaggio mapTipMessaggioEntityToTipMessaggio(TipMessaggioEntity tipMessaggioEntity) {
		if(tipMessaggioEntity == null) {
			return null;
		}

		//--- Generic mapping 
		TipMessaggio tipMessaggio = map(tipMessaggioEntity, TipMessaggio.class);

		return tipMessaggio;
	}
	
	/**
	 * Mapping from 'TipMessaggio' to 'TipMessaggioEntity'
	 * @param tipMessaggio
	 * @param tipMessaggioEntity
	 */
	public void mapTipMessaggioToTipMessaggioEntity(TipMessaggio tipMessaggio, TipMessaggioEntity tipMessaggioEntity) {
		if(tipMessaggio == null) {
			return;
		}

		//--- Generic mapping 
		map(tipMessaggio, tipMessaggioEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}