/*
 * Created on 13 lug 2017 ( Time 12:07:28 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.whitepaper.business.service.custom;

public interface MessaggioTagCustomService { 

	//cancellazione tags per idMsg
	int deleteTagsPerIdMsg(Integer idMsg);
	
	
}
