/*
 * Created on 13 lug 2017 ( Time 12:07:28 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.whitepaper.business.service.custom;

import org.whitepaper.bean.MessaggioSegnalato;

public interface MessaggioSegnalatoCustomService { 

	
	//salvataggio del messaggio segnalato		
	MessaggioSegnalato insertMsgSegnalato(Integer idMsg, String desMot, Integer idUteSegnalatore);
	
	//conferma della segnalazione messaggio offensivo
	boolean confermaSegnalazione(Integer idMsgSegn, Integer idMsg);
		
	int deleteMsgPerIdMsg(Integer idMsg);
	
}
