/*
 * Created on 13 lug 2017 ( Time 12:07:28 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.whitepaper.business.service.custom;

import java.util.Date;
import java.util.List;

import org.whitepaper.data.repository.jpa.custom.AggregateMsgPerDatPub;

public interface MessaggioStatCustomService { 

	
	//conta numero messaggi per data e tipo
	public List<AggregateMsgPerDatPub> countNumMessaggiPerTipoAfterDataIn(String codTipMsg, Date dataAfter);			
	
}
