/*
 * Created on 13 lug 2017 ( Time 12:07:28 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.whitepaper.business.service.impl.custom;

import javax.annotation.Resource;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;
import org.whitepaper.business.service.custom.MessaggioTagCustomService;
import org.whitepaper.data.repository.jpa.MessaggioTagsJpaRepository;

/**
 * Implementation of AnaUtenteService
 */
@Component
@Transactional(rollbackFor = Exception.class)
public class MessaggioTagCustomServiceImpl implements MessaggioTagCustomService {

	private static Logger logger = LoggerFactory.getLogger(MessaggioTagCustomServiceImpl.class);

	@Resource
	private MessaggioTagsJpaRepository messaggioTagsJpaRepository;

	//cancellazione tag per idMsg
	public int deleteTagsPerIdMsg(Integer idMsg) {

		int numRedDel = 0;	
		try {			
			numRedDel = messaggioTagsJpaRepository.deleteByMessaggioIdMsg(idMsg);
			
		} catch (Exception ex) {
			logger.error("******deleteTagsPerIdMsg: errore: " + ex.getMessage() );
		}		
		
		return numRedDel;
	}
}
