/*
 * Created on 2022-11-08 ( Time 12:43:44 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
// This Bean has a basic Primary Key (not composite) 

package org.whitepaper.bean;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;



public class MessaggioStat {

    private Integer id;
    private Date dataUltMovMsg;
    private String codTipMsg;
    private int numMsg;
    private Date datUltMov;
    private String codPgmUltMov;
    
    private String desNotMsg;
    
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public Date getDataUltMovMsg() {
		return dataUltMovMsg;
	}
	public void setDataUltMovMsg(Date dataUltMovMsg) {
		this.dataUltMovMsg = dataUltMovMsg;
	}
	public String getCodTipMsg() {
		return codTipMsg;
	}
	public void setCodTipMsg(String codTipMsg) {
		this.codTipMsg = codTipMsg;
	}
	public int getNumMsg() {
		return numMsg;
	}
	public void setNumMsg(int numMsg) {
		this.numMsg = numMsg;
	}
	public Date getDatUltMov() {
		return datUltMov;
	}
	public void setDatUltMov(Date datUltMov) {
		this.datUltMov = datUltMov;
	}
	public String getCodPgmUltMov() {
		return codPgmUltMov;
	}
	public void setCodPgmUltMov(String codPgmUltMov) {
		this.codPgmUltMov = codPgmUltMov;
	}
    
    
   
}
