/*
 * Created on 9 gen 2023 ( Time 14:38:49 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.whitepaper.web.listitem;

import org.whitepaper.bean.CatMessaggio;
import org.whitepaper.web.common.ListItem;

public class CatMessaggioListItem implements ListItem {

	private final String value ;
	private final String label ;
	
	public CatMessaggioListItem(CatMessaggio catMessaggio) {
		super();

		this.value = ""
			 + catMessaggio.getCatMsg()
		;

		//TODO : Define here the attributes to be displayed as the label
		this.label = catMessaggio.toString();
	}

	@Override
	public String getValue() {
		return value;
	}

	@Override
	public String getLabel() {
		return label;
	}

}
