/*
 * Created on 2022-11-03 ( Time 15:20:00 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
package org.whitepaper.web.listitem;

import org.whitepaper.bean.MessaggioTags;
import org.whitepaper.web.common.ListItem;

public class MessaggioTagsListItem implements ListItem {

	private final String value ;
	private final String label ;
	
	public MessaggioTagsListItem(MessaggioTags messaggioTags) {
		super();

		this.value = ""
			 + messaggioTags.getIdTag()
		;

		//TODO : Define here the attributes to be displayed as the label
		this.label = messaggioTags.toString();
	}

	@Override
	public String getValue() {
		return value;
	}

	@Override
	public String getLabel() {
		return label;
	}

}
