/*
 * Created on 2022-11-03 ( Time 15:19:59 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
package org.whitepaper.web.listitem;

import org.whitepaper.bean.Messaggio;
import org.whitepaper.web.common.ListItem;

public class MessaggioListItem implements ListItem {

	private final String value ;
	private final String label ;
	
	public MessaggioListItem(Messaggio messaggio) {
		super();

		this.value = ""
			 + messaggio.getIdMsg()
		;

		//TODO : Define here the attributes to be displayed as the label
		this.label = messaggio.toString();
	}

	@Override
	public String getValue() {
		return value;
	}

	@Override
	public String getLabel() {
		return label;
	}

}
