/*
 * Created on 19 gen 2023 ( Time 08:35:16 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.whitepaper.web.listitem;

import org.whitepaper.bean.MessaggioSegnalato;
import org.whitepaper.web.common.ListItem;

public class MessaggioSegnalatoListItem implements ListItem {

	private final String value ;
	private final String label ;
	
	public MessaggioSegnalatoListItem(MessaggioSegnalato messaggioSegnalato) {
		super();

		this.value = ""
			 + messaggioSegnalato.getIdMsgSegn()
		;

		//TODO : Define here the attributes to be displayed as the label
		this.label = messaggioSegnalato.toString();
	}

	@Override
	public String getValue() {
		return value;
	}

	@Override
	public String getLabel() {
		return label;
	}

}
