/*
 * Created on 2022-11-03 ( Time 15:20:01 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
package org.whitepaper.web.listitem;

import org.whitepaper.bean.TipProfilo;
import org.whitepaper.web.common.ListItem;

public class TipProfiloListItem implements ListItem {

	private final String value ;
	private final String label ;
	
	public TipProfiloListItem(TipProfilo tipProfilo) {
		super();

		this.value = ""
			 + tipProfilo.getCodTipPrf()
		;

		//TODO : Define here the attributes to be displayed as the label
		this.label = tipProfilo.toString();
	}

	@Override
	public String getValue() {
		return value;
	}

	@Override
	public String getLabel() {
		return label;
	}

}
