/*
 * Created on 6 nov 2017 ( Time 22:59:10 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.whitepaper.bean;

import java.io.Serializable;

import javax.validation.constraints.*;


public class ComboBean implements Serializable {

    private static final long serialVersionUID = 1L;

    public ComboBean(String codice, String descrizione) {
    	this.codice = codice;
    	this.descrizione = descrizione;
    }
        
    @Size( max = 20 )
    private String codice;

    @Size( max = 50 )
    private String descrizione;

	public String getCodice() {
		return codice;
	}

	public void setCodice(String codice) {
		this.codice = codice;
	}

	public String getDescrizione() {
		return descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

    
}
