/*
 * Created on 2022-11-08 ( Time 12:43:44 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
// This Bean has a basic Primary Key (not composite) 

package org.whitepaper.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;
import java.util.List;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "ana_utente"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="ana_utente", catalog="fogliobianco" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="AnaUtenteEntity.countAll", query="SELECT COUNT(x) FROM AnaUtenteEntity x" )
} )
public class AnaUtenteEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="ID_UTE", nullable=false)
    private Integer    idUte        ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="EMAIL", nullable=false, length=250)
    private String     email        ;

    @Column(name="PWD", nullable=false, length=60)
    private String     pwd          ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DAT_CRE_UTE")
    private Date       datCreUte    ;

    @Column(name="CON_UID", length=45)
    private String     conUid       ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dat_ult_mov")
    private Date       datUltMov    ;

	// "codTipPrf" (column "cod_tip_prf") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @OneToMany(mappedBy="anaUtente", targetEntity=MessaggioEntity.class)
    private List<MessaggioEntity> listOfMessaggio2;

    @ManyToOne
    @JoinColumn(name="cod_tip_prf", referencedColumnName="cod_tip_prf")
    private TipProfiloEntity tipProfilo  ;

    @OneToMany(mappedBy="anaUtente2", targetEntity=MessaggioEntity.class)
    private List<MessaggioEntity> listOfMessaggio;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public AnaUtenteEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setIdUte( Integer idUte ) {
        this.idUte = idUte ;
    }
    public Integer getIdUte() {
        return this.idUte;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : EMAIL ( VARCHAR ) 
    public void setEmail( String email ) {
        this.email = email;
    }
    public String getEmail() {
        return this.email;
    }

    //--- DATABASE MAPPING : PWD ( VARCHAR ) 
    public void setPwd( String pwd ) {
        this.pwd = pwd;
    }
    public String getPwd() {
        return this.pwd;
    }

    //--- DATABASE MAPPING : DAT_CRE_UTE ( DATE ) 
    public void setDatCreUte( Date datCreUte ) {
        this.datCreUte = datCreUte;
    }
    public Date getDatCreUte() {
        return this.datCreUte;
    }

    //--- DATABASE MAPPING : CON_UID ( VARCHAR ) 
    public void setConUid( String conUid ) {
        this.conUid = conUid;
    }
    public String getConUid() {
        return this.conUid;
    }

    //--- DATABASE MAPPING : dat_ult_mov ( DATETIME ) 
    public void setDatUltMov( Date datUltMov ) {
        this.datUltMov = datUltMov;
    }
    public Date getDatUltMov() {
        return this.datUltMov;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setListOfMessaggio2( List<MessaggioEntity> listOfMessaggio2 ) {
        this.listOfMessaggio2 = listOfMessaggio2;
    }
    public List<MessaggioEntity> getListOfMessaggio2() {
        return this.listOfMessaggio2;
    }

    public void setTipProfilo( TipProfiloEntity tipProfilo ) {
        this.tipProfilo = tipProfilo;
    }
    public TipProfiloEntity getTipProfilo() {
        return this.tipProfilo;
    }

    public void setListOfMessaggio( List<MessaggioEntity> listOfMessaggio ) {
        this.listOfMessaggio = listOfMessaggio;
    }
    public List<MessaggioEntity> getListOfMessaggio() {
        return this.listOfMessaggio;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(idUte);
        sb.append("]:"); 
        sb.append(email);
        sb.append("|");
        sb.append(pwd);
        sb.append("|");
        sb.append(datCreUte);
        sb.append("|");
        sb.append(conUid);
        sb.append("|");
        sb.append(datUltMov);
        return sb.toString(); 
    } 

}
