/*
 * Created on 9 gen 2023 ( Time 14:26:04 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package org.whitepaper.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Persistent class for entity stored in table "messaggio_admin"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="messaggio_admin", catalog="fogliobianco" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="MessaggioAdminEntity.countAll", query="SELECT COUNT(x) FROM MessaggioAdminEntity x" )
} )
public class MessaggioAdminEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id_msg", nullable=false)
    private Integer    idMsg        ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="des_msg", nullable=false, length=500)
    private String     desMsg       ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dat_ult_mov")
    private Date       datUltMov    ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dat_inizio_val")
    private Date       datInizioVal ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dat_fine_val")
    private Date       datFineVal   ;

	// "codTipMsg" (column "cod_tip_msg") is not defined by itself because used as FK in a link 
	// "catMsg" (column "cat_msg") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="cod_tip_msg", referencedColumnName="cod_tip_msg")
    private TipMessaggioEntity tipMessaggio;

    @ManyToOne
    @JoinColumn(name="cat_msg", referencedColumnName="cat_msg")
    private CatMessaggioEntity catMessaggio;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public MessaggioAdminEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setIdMsg( Integer idMsg ) {
        this.idMsg = idMsg ;
    }
    public Integer getIdMsg() {
        return this.idMsg;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : des_msg ( VARCHAR ) 
    public void setDesMsg( String desMsg ) {
        this.desMsg = desMsg;
    }
    public String getDesMsg() {
        return this.desMsg;
    }

    //--- DATABASE MAPPING : dat_ult_mov ( DATETIME ) 
    public void setDatUltMov( Date datUltMov ) {
        this.datUltMov = datUltMov;
    }
    public Date getDatUltMov() {
        return this.datUltMov;
    }

    //--- DATABASE MAPPING : dat_inizio_val ( DATETIME ) 
    public void setDatInizioVal( Date datInizioVal ) {
        this.datInizioVal = datInizioVal;
    }
    public Date getDatInizioVal() {
        return this.datInizioVal;
    }

    //--- DATABASE MAPPING : dat_fine_val ( DATETIME ) 
    public void setDatFineVal( Date datFineVal ) {
        this.datFineVal = datFineVal;
    }
    public Date getDatFineVal() {
        return this.datFineVal;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setTipMessaggio( TipMessaggioEntity tipMessaggio ) {
        this.tipMessaggio = tipMessaggio;
    }
    public TipMessaggioEntity getTipMessaggio() {
        return this.tipMessaggio;
    }

    public void setCatMessaggio( CatMessaggioEntity catMessaggio ) {
        this.catMessaggio = catMessaggio;
    }
    public CatMessaggioEntity getCatMessaggio() {
        return this.catMessaggio;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(idMsg);
        sb.append("]:"); 
        sb.append(desMsg);
        sb.append("|");
        sb.append(datUltMov);
        sb.append("|");
        sb.append(datInizioVal);
        sb.append("|");
        sb.append(datFineVal);
        return sb.toString(); 
    } 

}
