/*
 * Created on 2022-11-08 ( Time 12:43:44 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
// This Bean has a basic Primary Key (not composite) 

package org.whitepaper.bean.jpa;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;


@Entity
@Table(name = "messaggio_stat")
public class MessaggioStatEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Integer id;

    @Column(name = "data_ult_mov_msg", nullable = false)
    private Date dataUltMovMsg;

    @Column(name = "cod_tip_msg", nullable = false)
    private String codTipMsg;

    @Column(name = "num_msg", columnDefinition = "int default 0")
    private int numMsg;

    @Column(name = "dat_ult_mov", nullable = false)
    private Date datUltMov;

    @Column(name = "cod_pgm_ult_mov")
    private String c;
    
    @Column(name = "des_not_msg")
    private String desNotMsg;

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Date getDataUltMovMsg() {
		return dataUltMovMsg;
	}

	public void setDataUltMovMsg(Date dataUltMovMsg) {
		this.dataUltMovMsg = dataUltMovMsg;
	}

	public String getCodTipMsg() {
		return codTipMsg;
	}

	public void setCodTipMsg(String codTipMsg) {
		this.codTipMsg = codTipMsg;
	}

	public int getNumMsg() {
		return numMsg;
	}

	public void setNumMsg(int numMsg) {
		this.numMsg = numMsg;
	}

	public Date getDatUltMov() {
		return datUltMov;
	}

	public void setDatUltMov(Date datUltMov) {
		this.datUltMov = datUltMov;
	}

	public String getCodPgmUltMov() {
		return codPgmUltMov;
	}

	public void setCodPgmUltMov(String codPgmUltMov) {
		this.codPgmUltMov = codPgmUltMov;
	}

	public String getDesNotMsg() {
		return desNotMsg;
	}

	public void setDesNotMsg(String desNotMsg) {
		this.desNotMsg = desNotMsg;
	}

	    
    

   
}
