/*
 * Created on 22 nov 2022 ( Time 14:07:51 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package org.whitepaper.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Persistent class for entity stored in table "messaggio"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="messaggio", catalog="fogliobianco" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="MessaggioEntity.countAll", query="SELECT COUNT(x) FROM MessaggioEntity x" )
} )
public class MessaggioEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id_msg", nullable=false)
    private Integer    idMsg        ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="des_msg", length=1000)
    private String     desMsg       ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dat_ult_mov", nullable=false)
    private Date       datUltMov    ;
        
    @Column(name="id_foglio", nullable=false)
    private Integer    idFoglio;
    
    @Column(name="id_msg_reply", nullable=false)
    private Integer    idMsgReply        ;
    
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="data_pub", nullable=true)
    private Date       dataPub    ;

    
	// "idUteAut" (column "id_ute_aut") is not defined by itself because used as FK in a link 
	// "idUteReply" (column "id_ute_reply") is not defined by itself because used as FK in a link 
	// "codTipMsg" (column "cod_tip_msg") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @OneToMany(mappedBy="messaggio", targetEntity=MessaggioTagsEntity.class)
    private List<MessaggioTagsEntity> listOfMessaggioTags;

    @ManyToOne
    @JoinColumn(name="id_ute_aut", referencedColumnName="ID_UTE")
    private AnaUtenteEntity anaUtente   ;

    @ManyToOne
    @JoinColumn(name="id_ute_reply", referencedColumnName="ID_UTE")
    private AnaUtenteEntity anaUtente2  ;

    @ManyToOne
    @JoinColumn(name="cod_tip_msg", referencedColumnName="cod_tip_msg")
    private TipMessaggioEntity tipMessaggio;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public MessaggioEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setIdMsg( Integer idMsg ) {
        this.idMsg = idMsg ;
    }
    public Integer getIdMsg() {
        return this.idMsg;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : des_msg ( VARCHAR ) 
    public void setDesMsg( String desMsg ) {
        this.desMsg = desMsg;
    }
    public String getDesMsg() {
        return this.desMsg;
    }

    //--- DATABASE MAPPING : dat_ult_mov ( DATETIME ) 
    public void setDatUltMov( Date datUltMov ) {
        this.datUltMov = datUltMov;
    }
    public Date getDatUltMov() {
        return this.datUltMov;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setListOfMessaggioTags( List<MessaggioTagsEntity> listOfMessaggioTags ) {
        this.listOfMessaggioTags = listOfMessaggioTags;
    }
    public List<MessaggioTagsEntity> getListOfMessaggioTags() {
        return this.listOfMessaggioTags;
    }

    public void setAnaUtente( AnaUtenteEntity anaUtente ) {
        this.anaUtente = anaUtente;
    }
    public AnaUtenteEntity getAnaUtente() {
        return this.anaUtente;
    }

    public void setAnaUtente2( AnaUtenteEntity anaUtente2 ) {
        this.anaUtente2 = anaUtente2;
    }
    public AnaUtenteEntity getAnaUtente2() {
        return this.anaUtente2;
    }

    public void setTipMessaggio( TipMessaggioEntity tipMessaggio ) {
        this.tipMessaggio = tipMessaggio;
    }
    public TipMessaggioEntity getTipMessaggio() {
        return this.tipMessaggio;
    }

    


	//----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(idMsg);
        sb.append("]:"); 
        sb.append(desMsg);
        sb.append("|");
        sb.append(datUltMov);
        return sb.toString(); 
    }

	public Integer getIdFoglio() {
		return idFoglio;
	}

	public void setIdFoglio(Integer idFoglio) {
		this.idFoglio = idFoglio;
	}

	public Integer getIdMsgReply() {
		return idMsgReply;
	}

	public void setIdMsgReply(Integer idMsgReply) {
		this.idMsgReply = idMsgReply;
	}

	public Date getDataPub() {
		return dataPub;
	}

	public void setDataPub(Date dataPub) {
		this.dataPub = dataPub;
	} 


	
	
}
