/*
 * Created on 2022-11-03 ( Time 15:16:05 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
// This Bean has a basic Primary Key (not composite) 

package org.whitepaper.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "messaggio_tags"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="messaggio_tags", catalog="fogliobianco" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="MessaggioTagsEntity.countAll", query="SELECT COUNT(x) FROM MessaggioTagsEntity x" )
} )
public class MessaggioTagsEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id_tag", nullable=false)
    private Integer    idTag        ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="tag", nullable=false, length=50)
    private String     tag          ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dat_ult_mov")
    private Date       datUltMov    ;

	// "idMsg" (column "id_msg") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="id_msg", referencedColumnName="id_msg")
    private MessaggioEntity messaggio   ;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public MessaggioTagsEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setIdTag( Integer idTag ) {
        this.idTag = idTag ;
    }
    public Integer getIdTag() {
        return this.idTag;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : tag ( VARCHAR ) 
    public void setTag( String tag ) {
        this.tag = tag;
    }
    public String getTag() {
        return this.tag;
    }

    //--- DATABASE MAPPING : dat_ult_mov ( DATETIME ) 
    public void setDatUltMov( Date datUltMov ) {
        this.datUltMov = datUltMov;
    }
    public Date getDatUltMov() {
        return this.datUltMov;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setMessaggio( MessaggioEntity messaggio ) {
        this.messaggio = messaggio;
    }
    public MessaggioEntity getMessaggio() {
        return this.messaggio;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(idTag);
        sb.append("]:"); 
        sb.append(tag);
        sb.append("|");
        sb.append(datUltMov);
        return sb.toString(); 
    } 

}
