/*
 * Created on 2022-11-03 ( Time 15:16:05 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
// This Bean has a basic Primary Key (not composite) 

package org.whitepaper.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.List;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "tip_profilo"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="tip_profilo", catalog="fogliobianco" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="TipProfiloEntity.countAll", query="SELECT COUNT(x) FROM TipProfiloEntity x" )
} )
public class TipProfiloEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name="cod_tip_prf", nullable=false, length=10)
    private String     codTipPrf    ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="des_tip_prf", length=100)
    private String     desTipPrf    ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @OneToMany(mappedBy="tipProfilo", targetEntity=AnaUtenteEntity.class)
    private List<AnaUtenteEntity> listOfAnaUtente;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public TipProfiloEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setCodTipPrf( String codTipPrf ) {
        this.codTipPrf = codTipPrf ;
    }
    public String getCodTipPrf() {
        return this.codTipPrf;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : des_tip_prf ( VARCHAR ) 
    public void setDesTipPrf( String desTipPrf ) {
        this.desTipPrf = desTipPrf;
    }
    public String getDesTipPrf() {
        return this.desTipPrf;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setListOfAnaUtente( List<AnaUtenteEntity> listOfAnaUtente ) {
        this.listOfAnaUtente = listOfAnaUtente;
    }
    public List<AnaUtenteEntity> getListOfAnaUtente() {
        return this.listOfAnaUtente;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(codTipPrf);
        sb.append("]:"); 
        sb.append(desTipPrf);
        return sb.toString(); 
    } 

}
