/*
 * Created on 2022-11-08 ( Time 12:43:44 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
// This Bean has a basic Primary Key (not composite) 

package org.whitepaper.bean.jpa;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;


@Entity
@Table(name = "utente_action")
public class UtenteActionEntity {
	
	@Id
    @GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "id_ute_act", nullable = false)
	private int idUteAct;
	
    @Column(name = "id_ute", nullable = false)
    private int idUte;
	
    @Column(name = "cod_action", nullable = false, length = 10)
    private String codAction;

    @Column(name = "dat_action", nullable = false)    
    private Date datAction;
    
    @Column(name = "num_action", nullable = false)
    private int numAction;

    @Column(name = "dat_ult_mov")    
    private Date datUltMov;
    
	public int getIdUteAct() {
		return idUteAct;
	}

	public void setIdUteAct(int idUteAct) {
		this.idUteAct = idUteAct;
	}

	public int getIdUte() {
		return idUte;
	}

	public void setIdUte(int idUte) {
		this.idUte = idUte;
	}

	public String getCodAction() {
		return codAction;
	}

	public void setCodAction(String codAction) {
		this.codAction = codAction;
	}

	public Date getDatAction() {
		return datAction;
	}

	public void setDatAction(Date datAction) {
		this.datAction = datAction;
	}

	public Date getDatUltMov() {
		return datUltMov;
	}

	public void setDatUltMov(Date datUltMov) {
		this.datUltMov = datUltMov;
	}

	public int getNumAction() {
		return numAction;
	}

	public void setNumAction(int numAction) {
		this.numAction = numAction;
	}
	    
    

   
}
