/*
 * Created on 22 nov 2022 ( Time 14:08:09 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.whitepaper.business.service.impl;

import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;

import javax.annotation.Resource;

import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;
import org.whitepaper.bean.Messaggio;
import org.whitepaper.bean.jpa.MessaggioEntity;
import org.whitepaper.business.service.MessaggioService;
import org.whitepaper.business.service.mapping.MessaggioServiceMapper;
import org.whitepaper.data.repository.jpa.MessaggioJpaRepository;

/**
 * Implementation of MessaggioService
 */
@Component
@Transactional
public class MessaggioServiceImpl implements MessaggioService {

	@Resource
	private MessaggioJpaRepository messaggioJpaRepository;

	@Resource
	private MessaggioServiceMapper messaggioServiceMapper;
	
	@Override
	public Messaggio findById(Integer idMsg) {
		MessaggioEntity messaggioEntity = messaggioJpaRepository.findOne(idMsg);
		return messaggioServiceMapper.mapMessaggioEntityToMessaggio(messaggioEntity);
	}

	@Override
	public List<Messaggio> findAll() {
		Iterable<MessaggioEntity> entities = messaggioJpaRepository.findAll();
		List<Messaggio> beans = new ArrayList<Messaggio>();
		for(MessaggioEntity messaggioEntity : entities) {
			beans.add(messaggioServiceMapper.mapMessaggioEntityToMessaggio(messaggioEntity));
		}
		return beans;
	}

	@Override
	public Messaggio save(Messaggio messaggio) {
		return update(messaggio) ;
	}

	@Override
	public Messaggio create(Messaggio messaggio) {
		MessaggioEntity messaggioEntity = null; 
		if ( null!=messaggio && messaggio.getIdMsg()!=null )
			messaggioEntity = messaggioJpaRepository.findOne(messaggio.getIdMsg());
		
		if( messaggioEntity != null ) {
			throw new IllegalStateException("already.exists");
		}
		messaggioEntity = new MessaggioEntity();
		messaggioServiceMapper.mapMessaggioToMessaggioEntity(messaggio, messaggioEntity);
		messaggioEntity.setDatUltMov( Calendar.getInstance().getTime() );
		MessaggioEntity messaggioEntitySaved = messaggioJpaRepository.save(messaggioEntity);
		return messaggioServiceMapper.mapMessaggioEntityToMessaggio(messaggioEntitySaved);
	}

	@Override
	public Messaggio update(Messaggio messaggio) {
		MessaggioEntity messaggioEntity = messaggioJpaRepository.findOne(messaggio.getIdMsg());
		messaggioServiceMapper.mapMessaggioToMessaggioEntity(messaggio, messaggioEntity);
		messaggioEntity.setDatUltMov( Calendar.getInstance().getTime() );
		MessaggioEntity messaggioEntitySaved = messaggioJpaRepository.save(messaggioEntity);
		return messaggioServiceMapper.mapMessaggioEntityToMessaggio(messaggioEntitySaved);
	}

	@Override
	public void delete(Integer idMsg) {
		messaggioJpaRepository.delete(idMsg);
	}

	public MessaggioJpaRepository getMessaggioJpaRepository() {
		return messaggioJpaRepository;
	}

	public void setMessaggioJpaRepository(MessaggioJpaRepository messaggioJpaRepository) {
		this.messaggioJpaRepository = messaggioJpaRepository;
	}

	public MessaggioServiceMapper getMessaggioServiceMapper() {
		return messaggioServiceMapper;
	}

	public void setMessaggioServiceMapper(MessaggioServiceMapper messaggioServiceMapper) {
		this.messaggioServiceMapper = messaggioServiceMapper;
	}

}
