/*
 * Created on 26 set 2018 ( Time 10:26:25 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.whitepaper.web.common;

public interface ListItem {

	public String getValue();
	
	public String getLabel();
}
